-- So Bolao - modulo acoplado Turbo Tiger
-- Aplicacao manual/local: tools/supabase-cli/supabase.exe db query --linked --file "turbotiger-site/sobolao/database/mod_sobolao.sql"

create schema if not exists mod_sobolao;
comment on schema mod_sobolao is 'Modulo So Bolao: organizacao operacional de boloes lotericos do ecossistema Turbo Tiger.';

create table if not exists mod_sobolao.tbl_sbl_modalidades (
  cod_modalidade bigint generated by default as identity primary key,
  chave text not null unique,
  nome text not null,
  qtd_numeros integer not null,
  minimo_numero integer not null,
  maximo_numero integer not null,
  ativo boolean not null default true,
  regras_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint ck_sbl_modalidades_chave check (btrim(chave) <> ''),
  constraint ck_sbl_modalidades_intervalo check (minimo_numero > 0 and maximo_numero >= minimo_numero and qtd_numeros > 0)
);

create table if not exists mod_sobolao.tbl_sbl_lotericas (
  cod_loterica bigint generated by default as identity primary key,
  nome text not null,
  cnpj text not null unique,
  cidade text,
  uf text,
  endereco text,
  whatsapp text,
  email text,
  status text not null default 'analise',
  contrato_url text,
  dados_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint ck_sbl_lotericas_cnpj check (cnpj ~ '^[0-9]{14}$'),
  constraint ck_sbl_lotericas_status check (status in ('analise','ativa','pausada','bloqueada'))
);

create table if not exists mod_sobolao.tbl_sbl_loterica_usuarios (
  cod_loterica_usuario bigint generated by default as identity primary key,
  id_loterica bigint not null references mod_sobolao.tbl_sbl_lotericas(cod_loterica) on delete cascade,
  uid_usuario uuid not null references auth.users(id) on delete cascade,
  email text,
  nome text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_loterica, uid_usuario)
);

create table if not exists mod_sobolao.tbl_sbl_concursos (
  cod_concurso bigint generated by default as identity primary key,
  id_modalidade bigint not null references mod_sobolao.tbl_sbl_modalidades(cod_modalidade),
  numero integer not null,
  data_sorteio date not null,
  status text not null default 'programado',
  resultado_json jsonb not null default '[]'::jsonb,
  premio_estimado_centavos bigint not null default 0,
  apurado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_modalidade, numero),
  constraint ck_sbl_concursos_numero check (numero > 0),
  constraint ck_sbl_concursos_status check (status in ('programado','registrado','apurado','cancelado'))
);

create table if not exists mod_sobolao.tbl_sbl_boloes (
  cod_bolao bigint generated by default as identity primary key,
  codigo_publico text not null unique default ('sbl_' || substr(replace((extensions.gen_random_uuid())::text, '-', ''), 1, 12)),
  id_concurso bigint not null references mod_sobolao.tbl_sbl_concursos(cod_concurso),
  id_loterica bigint references mod_sobolao.tbl_sbl_lotericas(cod_loterica),
  titulo text not null,
  status text not null default 'rascunho',
  qtd_cotas integer not null,
  valor_aposta_cota_centavos integer not null,
  taxa_gestao_percentual numeric(7,3) not null default 10,
  data_limite timestamptz not null,
  numeros_json jsonb not null default '[]'::jsonb,
  comprovante_url text,
  regras_json jsonb not null default '{}'::jsonb,
  observacao text,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint ck_sbl_boloes_status check (status in ('rascunho','aberto','fechando','registrado','apurado','encerrado','cancelado')),
  constraint ck_sbl_boloes_cotas check (qtd_cotas > 0),
  constraint ck_sbl_boloes_valor check (valor_aposta_cota_centavos > 0 and taxa_gestao_percentual >= 0)
);

create table if not exists mod_sobolao.tbl_sbl_participacoes (
  cod_participacao bigint generated by default as identity primary key,
  codigo_participacao text not null unique default ('sblp_' || substr(replace((extensions.gen_random_uuid())::text, '-', ''), 1, 14)),
  id_bolao bigint not null references mod_sobolao.tbl_sbl_boloes(cod_bolao) on delete cascade,
  id_usuario bigint not null references public.tbl_usuarios(cod_usuario) on delete cascade,
  qtd_cotas integer not null,
  valor_aposta_centavos bigint not null,
  taxa_gestao_centavos bigint not null,
  valor_total_centavos bigint not null,
  status text not null default 'reservado',
  metodo_pagamento text,
  pagamento_ref text,
  palpite_numeros_json jsonb not null default '[]'::jsonb,
  documento_url text,
  reservado_em timestamptz not null default now(),
  pago_em timestamptz,
  cancelado_em timestamptz,
  atualizado_em timestamptz not null default now(),
  constraint ck_sbl_participacoes_cotas check (qtd_cotas > 0),
  constraint ck_sbl_participacoes_valores check (valor_aposta_centavos >= 0 and taxa_gestao_centavos >= 0 and valor_total_centavos = valor_aposta_centavos + taxa_gestao_centavos),
  constraint ck_sbl_participacoes_status check (status in ('reservado','pago','confirmado','cancelado','estornado','premiado','encerrado'))
);

create table if not exists mod_sobolao.tbl_sbl_premios (
  cod_premio bigint generated by default as identity primary key,
  id_bolao bigint not null references mod_sobolao.tbl_sbl_boloes(cod_bolao) on delete cascade,
  faixa text not null,
  acertos integer,
  valor_total_centavos bigint not null default 0,
  status text not null default 'apurando',
  documento_url text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint ck_sbl_premios_status check (status in ('apurando','confirmado','pago','cancelado'))
);

create table if not exists mod_sobolao.tbl_sbl_rateios (
  cod_rateio bigint generated by default as identity primary key,
  id_premio bigint not null references mod_sobolao.tbl_sbl_premios(cod_premio) on delete cascade,
  id_participacao bigint not null references mod_sobolao.tbl_sbl_participacoes(cod_participacao) on delete cascade,
  id_usuario bigint not null references public.tbl_usuarios(cod_usuario) on delete cascade,
  qtd_cotas integer not null,
  valor_centavos bigint not null default 0,
  status text not null default 'pendente',
  pago_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_premio, id_participacao),
  constraint ck_sbl_rateios_status check (status in ('pendente','confirmado','pago','cancelado'))
);

create table if not exists mod_sobolao.tbl_sbl_documentos (
  cod_documento bigint generated by default as identity primary key,
  alvo_tipo text not null,
  alvo_id bigint not null,
  tipo text not null,
  url text not null,
  hash_sha256 text,
  observacao text,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  constraint ck_sbl_documentos_alvo check (alvo_tipo in ('bolao','participacao','loterica','premio','rateio')),
  constraint ck_sbl_documentos_tipo check (btrim(tipo) <> '' and btrim(url) <> '')
);

create table if not exists mod_sobolao.tbl_sbl_chamados (
  cod_chamado bigint generated by default as identity primary key,
  uid_origem uuid references auth.users(id) on delete set null,
  id_usuario bigint references public.tbl_usuarios(cod_usuario) on delete set null,
  id_loterica bigint references mod_sobolao.tbl_sbl_lotericas(cod_loterica) on delete set null,
  id_bolao bigint references mod_sobolao.tbl_sbl_boloes(cod_bolao) on delete set null,
  origem text not null default 'usuario',
  assunto text not null,
  mensagem text not null,
  prioridade text not null default 'media',
  status text not null default 'aberto',
  mensagens_json jsonb not null default '[]'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  encerrado_em timestamptz,
  constraint ck_sbl_chamados_status check (status in ('aberto','em_atendimento','respondido','encerrado','cancelado')),
  constraint ck_sbl_chamados_prioridade check (prioridade in ('baixa','media','alta','critica'))
);

create table if not exists mod_sobolao.tbl_sbl_auditoria (
  cod_auditoria bigint generated by default as identity primary key,
  uid_usuario uuid,
  area text not null,
  acao text not null,
  alvo_tipo text,
  alvo_id text,
  detalhes_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists ix_sbl_boloes_status_limite on mod_sobolao.tbl_sbl_boloes(status, data_limite);
create index if not exists ix_sbl_boloes_concurso on mod_sobolao.tbl_sbl_boloes(id_concurso);
create index if not exists ix_sbl_participacoes_usuario on mod_sobolao.tbl_sbl_participacoes(id_usuario, atualizado_em desc);
create index if not exists ix_sbl_participacoes_bolao_status on mod_sobolao.tbl_sbl_participacoes(id_bolao, status);
create index if not exists ix_sbl_rateios_usuario on mod_sobolao.tbl_sbl_rateios(id_usuario, criado_em desc);
create index if not exists ix_sbl_chamados_status on mod_sobolao.tbl_sbl_chamados(status, atualizado_em desc);
create index if not exists ix_sbl_auditoria_area_criado on mod_sobolao.tbl_sbl_auditoria(area, criado_em desc);

create or replace function mod_sobolao.trg_sbl_atualizado()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

do $$
declare
  r record;
begin
  for r in
    select unnest(array[
      'tbl_sbl_modalidades',
      'tbl_sbl_lotericas',
      'tbl_sbl_loterica_usuarios',
      'tbl_sbl_concursos',
      'tbl_sbl_boloes',
      'tbl_sbl_participacoes',
      'tbl_sbl_premios',
      'tbl_sbl_rateios',
      'tbl_sbl_chamados'
    ]) as tabela
  loop
    execute format('drop trigger if exists trg_%s_atualizado on mod_sobolao.%I', r.tabela, r.tabela);
    execute format('create trigger trg_%s_atualizado before update on mod_sobolao.%I for each row execute function mod_sobolao.trg_sbl_atualizado()', r.tabela, r.tabela);
  end loop;
end $$;

insert into mod_sobolao.tbl_sbl_modalidades (chave, nome, qtd_numeros, minimo_numero, maximo_numero, regras_json)
values
  ('mega_sena', 'Mega-Sena', 6, 1, 60, '{"volantes_padrao": 6}'::jsonb),
  ('lotofacil', 'Lotofacil', 15, 1, 25, '{"volantes_padrao": 15}'::jsonb),
  ('quina', 'Quina', 5, 1, 80, '{"volantes_padrao": 5}'::jsonb)
on conflict (chave) do update
set nome = excluded.nome,
    qtd_numeros = excluded.qtd_numeros,
    minimo_numero = excluded.minimo_numero,
    maximo_numero = excluded.maximo_numero,
    regras_json = excluded.regras_json,
    ativo = true,
    atualizado_em = now();

insert into mod_admin.tbl_adm_areas (chave, nome, descricao, ativo, ordem)
values ('sobolao', 'So Bolao', 'Administracao, suporte e operacao do modulo So Bolao.', true, 30)
on conflict (chave) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    ativo = true,
    ordem = excluded.ordem,
    atualizado_em = now();

insert into mod_admin.tbl_adm_perfis (chave, nome, descricao, permissoes_json, ativo)
values
  (
    'sobolao_operador',
    'Operador So Bolao',
    'Acesso operacional ao modulo So Bolao.',
    '{"areas":["sobolao"],"sobolao":{"acessar":true,"boloes":true,"lotericas":true,"suporte":true,"financeiro":true}}'::jsonb,
    true
  ),
  (
    'sobolao_suporte',
    'Suporte So Bolao',
    'Acesso de atendimento e conferencia do modulo So Bolao.',
    '{"areas":["sobolao"],"sobolao":{"acessar":true,"boloes":false,"lotericas":false,"suporte":true,"financeiro":false}}'::jsonb,
    true
  )
on conflict (chave) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    permissoes_json = excluded.permissoes_json,
    ativo = true,
    atualizado_em = now();

create or replace function mod_sobolao.fn_sbl_usuario_atual()
returns bigint
language plpgsql
stable
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_id_usuario bigint;
begin
  if v_uid is null then
    return null;
  end if;

  select u.cod_usuario
    into v_id_usuario
  from public.tbl_usuarios u
  where u.uid_usuario = v_uid
  limit 1;

  return v_id_usuario;
end;
$$;

create or replace function mod_sobolao.fn_sbl_admin_ok(p_acao text default 'acessar')
returns boolean
language plpgsql
stable
security definer
set search_path to 'mod_sobolao', 'mod_admin', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_ok boolean := false;
begin
  if v_uid is null then
    return false;
  end if;

  select coalesce((select p.ok from mod_admin.fn_adm_usuario_tem_permissao(v_uid, 'sobolao', coalesce(p_acao, 'acessar')) p limit 1), false)
      or coalesce((select p.ok from mod_admin.fn_adm_usuario_tem_permissao(v_uid, 'admin', 'acessar') p limit 1), false)
    into v_ok;

  return coalesce(v_ok, false);
end;
$$;

create or replace function public.sobolao_usuario_painel_rpc()
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_id_usuario bigint;
  v_resumo jsonb;
  v_boloes jsonb;
  v_minhas jsonb;
  v_resultados jsonb;
  v_premios jsonb;
  v_chamados jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;

  v_id_usuario := mod_sobolao.fn_sbl_usuario_atual();
  if v_id_usuario is null then
    return jsonb_build_object('ok', false, 'error', 'usuario_nao_encontrado');
  end if;

  select jsonb_build_object(
    'boloes_ativos', (select count(*) from mod_sobolao.tbl_sbl_boloes b where b.status in ('aberto','fechando','registrado')),
    'cotas_reservadas', coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p where p.id_usuario = v_id_usuario and p.status in ('reservado','pago','confirmado','premiado')), 0),
    'premios_centavos', coalesce((select sum(r.valor_centavos) from mod_sobolao.tbl_sbl_rateios r where r.id_usuario = v_id_usuario and r.status in ('confirmado','pago')), 0),
    'gestao_centavos', coalesce((select sum(p.taxa_gestao_centavos) from mod_sobolao.tbl_sbl_participacoes p where p.id_usuario = v_id_usuario and p.status in ('reservado','pago','confirmado','premiado')), 0),
    'parceiras', (select count(*) from mod_sobolao.tbl_sbl_lotericas l where l.status = 'ativa'),
    'pendencias', coalesce((select count(*) from mod_sobolao.tbl_sbl_participacoes p where p.id_usuario = v_id_usuario and p.status = 'reservado'), 0),
    'taxa_gestao_percentual', 10,
    'conversao_alvo_percentual', 30,
    'apostas_media_mes', 4,
    'ticket_oficial_centavos', 600
  ) into v_resumo;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.data_limite), '[]'::jsonb)
    into v_boloes
  from (
    select
      b.cod_bolao,
      b.titulo,
      m.nome as modalidade,
      m.chave as modalidade_chave,
      c.numero as concurso,
      c.data_sorteio,
      b.data_limite,
      l.nome as loterica,
      l.cnpj as loterica_cnpj,
      b.qtd_cotas,
      coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p where p.id_bolao = b.cod_bolao and p.status in ('reservado','pago','confirmado','premiado')), 0) as cotas_reservadas,
      b.valor_aposta_cota_centavos,
      b.taxa_gestao_percentual,
      (b.valor_aposta_cota_centavos + round(b.valor_aposta_cota_centavos * b.taxa_gestao_percentual / 100.0)::integer) as valor_total_cota_centavos,
      b.status,
      b.numeros_json as numeros,
      b.comprovante_url
    from mod_sobolao.tbl_sbl_boloes b
    join mod_sobolao.tbl_sbl_concursos c on c.cod_concurso = b.id_concurso
    join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
    left join mod_sobolao.tbl_sbl_lotericas l on l.cod_loterica = b.id_loterica
    where b.status in ('aberto','fechando','registrado')
    order by b.data_limite
    limit 40
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.atualizado_em desc), '[]'::jsonb)
    into v_minhas
  from (
    select
      p.cod_participacao,
      b.titulo as bolao,
      m.nome as modalidade,
      c.numero as concurso,
      c.data_sorteio,
      p.qtd_cotas as cotas,
      p.valor_total_centavos,
      p.status,
      p.documento_url,
      p.atualizado_em
    from mod_sobolao.tbl_sbl_participacoes p
    join mod_sobolao.tbl_sbl_boloes b on b.cod_bolao = p.id_bolao
    join mod_sobolao.tbl_sbl_concursos c on c.cod_concurso = b.id_concurso
    join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
    where p.id_usuario = v_id_usuario
    order by p.atualizado_em desc
    limit 80
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.data_sorteio desc), '[]'::jsonb)
    into v_resultados
  from (
    select
      m.nome as modalidade,
      c.numero as concurso,
      c.data_sorteio,
      c.resultado_json as numeros,
      c.status,
      c.premio_estimado_centavos
    from mod_sobolao.tbl_sbl_concursos c
    join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
    where c.status = 'apurado'
    order by c.data_sorteio desc
    limit 20
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.criado_em desc), '[]'::jsonb)
    into v_premios
  from (
    select
      b.titulo as bolao,
      pr.faixa,
      pr.valor_total_centavos as total_centavos,
      r.valor_centavos as minha_parte_centavos,
      r.status,
      r.criado_em
    from mod_sobolao.tbl_sbl_rateios r
    join mod_sobolao.tbl_sbl_premios pr on pr.cod_premio = r.id_premio
    join mod_sobolao.tbl_sbl_boloes b on b.cod_bolao = pr.id_bolao
    where r.id_usuario = v_id_usuario
    order by r.criado_em desc
    limit 80
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.atualizado_em desc), '[]'::jsonb)
    into v_chamados
  from (
    select cod_chamado, assunto, prioridade, status, atualizado_em
    from mod_sobolao.tbl_sbl_chamados
    where id_usuario = v_id_usuario
    order by atualizado_em desc
    limit 30
  ) s;

  return jsonb_build_object(
    'ok', true,
    'resumo', v_resumo,
    'fluxo', jsonb_build_array(
      jsonb_build_object('titulo','Formacao','texto','Bolao aberto com cotas, modalidade, concurso e limite definidos.'),
      jsonb_build_object('titulo','Reserva','texto','Participante registra cota e pagamento fica rastreavel.'),
      jsonb_build_object('titulo','Repasse','texto','Valor oficial segue para a loterica parceira; taxa fica separada.'),
      jsonb_build_object('titulo','Documento','texto','Comprovante da aposta e auditoria ficam vinculados ao bolao.'),
      jsonb_build_object('titulo','Apuracao','texto','Resultado, premio e rateio proporcional sao registrados.')
    ),
    'modalidades', (select coalesce(jsonb_agg(jsonb_build_object('chave', chave, 'nome', nome) order by nome), '[]'::jsonb) from mod_sobolao.tbl_sbl_modalidades where ativo),
    'boloes', v_boloes,
    'minhas_participacoes', v_minhas,
    'resultados', v_resultados,
    'premios', v_premios,
    'chamados', v_chamados
  );
end;
$$;

create or replace function public.adm_sobolao_painel_rpc(p_periodo text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_admin boolean := mod_sobolao.fn_sbl_admin_ok('acessar');
  v_base jsonb;
  v_lotericas jsonb;
  v_fila_loterica jsonb;
  v_chamados jsonb;
  v_fila_admin jsonb;
begin
  if not v_admin then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_sobolao');
  end if;

  select jsonb_build_object(
    'ok', true,
    'resumo', jsonb_build_object(
      'boloes_ativos', (select count(*) from mod_sobolao.tbl_sbl_boloes b where b.status in ('aberto','fechando','registrado')),
      'cotas_reservadas', coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p where p.status in ('reservado','pago','confirmado','premiado')), 0),
      'premios_centavos', coalesce((select sum(pr.valor_total_centavos) from mod_sobolao.tbl_sbl_premios pr where pr.status in ('confirmado','pago')), 0),
      'gestao_centavos', coalesce((select sum(p.taxa_gestao_centavos) from mod_sobolao.tbl_sbl_participacoes p where p.status in ('reservado','pago','confirmado','premiado')), 0),
      'parceiras', (select count(*) from mod_sobolao.tbl_sbl_lotericas l where l.status = 'ativa'),
      'pendencias', coalesce((select count(*) from mod_sobolao.tbl_sbl_chamados c where c.status in ('aberto','em_atendimento')), 0),
      'taxa_gestao_percentual', 10,
      'conversao_alvo_percentual', 30,
      'apostas_media_mes', 4,
      'ticket_oficial_centavos', 600
    ),
    'fluxo', jsonb_build_array(
      jsonb_build_object('titulo','Formacao','texto','Bolao aberto com cotas, modalidade, concurso e limite definidos.'),
      jsonb_build_object('titulo','Reserva','texto','Participante registra cota e pagamento fica rastreavel.'),
      jsonb_build_object('titulo','Repasse','texto','Valor oficial segue para a loterica parceira; taxa fica separada.'),
      jsonb_build_object('titulo','Documento','texto','Comprovante da aposta e auditoria ficam vinculados ao bolao.'),
      jsonb_build_object('titulo','Apuracao','texto','Resultado, premio e rateio proporcional sao registrados.')
    ),
    'modalidades', (select coalesce(jsonb_agg(jsonb_build_object('chave', chave, 'nome', nome) order by nome), '[]'::jsonb) from mod_sobolao.tbl_sbl_modalidades where ativo),
    'boloes', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.data_limite), '[]'::jsonb)
      from (
        select
          b.cod_bolao,
          b.titulo,
          m.nome as modalidade,
          m.chave as modalidade_chave,
          c.numero as concurso,
          c.data_sorteio,
          b.data_limite,
          l.nome as loterica,
          l.cnpj as loterica_cnpj,
          b.qtd_cotas,
          coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p where p.id_bolao = b.cod_bolao and p.status in ('reservado','pago','confirmado','premiado')), 0) as cotas_reservadas,
          b.valor_aposta_cota_centavos,
          b.taxa_gestao_percentual,
          (b.valor_aposta_cota_centavos + round(b.valor_aposta_cota_centavos * b.taxa_gestao_percentual / 100.0)::integer) as valor_total_cota_centavos,
          b.status,
          b.numeros_json as numeros,
          b.comprovante_url
        from mod_sobolao.tbl_sbl_boloes b
        join mod_sobolao.tbl_sbl_concursos c on c.cod_concurso = b.id_concurso
        join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
        left join mod_sobolao.tbl_sbl_lotericas l on l.cod_loterica = b.id_loterica
        order by b.data_limite
        limit 80
      ) s
    ),
    'minhas_participacoes', '[]'::jsonb,
    'resultados', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.data_sorteio desc), '[]'::jsonb)
      from (
        select
          m.nome as modalidade,
          c.numero as concurso,
          c.data_sorteio,
          c.resultado_json as numeros,
          c.status,
          c.premio_estimado_centavos
        from mod_sobolao.tbl_sbl_concursos c
        join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
        where c.status = 'apurado'
        order by c.data_sorteio desc
        limit 30
      ) s
    ),
    'premios', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.criado_em desc), '[]'::jsonb)
      from (
        select
          b.titulo as bolao,
          pr.faixa,
          pr.valor_total_centavos as total_centavos,
          coalesce(sum(r.valor_centavos), 0) as minha_parte_centavos,
          pr.status,
          pr.criado_em
        from mod_sobolao.tbl_sbl_premios pr
        join mod_sobolao.tbl_sbl_boloes b on b.cod_bolao = pr.id_bolao
        left join mod_sobolao.tbl_sbl_rateios r on r.id_premio = pr.cod_premio
        group by pr.cod_premio, b.titulo
        order by pr.criado_em desc
        limit 80
      ) s
    )
  )
  into v_base;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.nome), '[]'::jsonb)
    into v_lotericas
  from (
    select
      l.cod_loterica,
      l.nome,
      l.cnpj,
      l.cidade,
      l.uf,
      l.whatsapp,
      l.status,
      (select count(*) from mod_sobolao.tbl_sbl_boloes b where b.id_loterica = l.cod_loterica and b.status in ('aberto','fechando','registrado')) as boloes_ativos,
      coalesce((select sum(b.valor_aposta_cota_centavos * p.qtd_cotas)
        from mod_sobolao.tbl_sbl_boloes b
        join mod_sobolao.tbl_sbl_participacoes p on p.id_bolao = b.cod_bolao
        where b.id_loterica = l.cod_loterica and p.status in ('pago','confirmado')), 0) as repasse_pendente_centavos
    from mod_sobolao.tbl_sbl_lotericas l
    order by l.nome
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.status, s.bolao), '[]'::jsonb)
    into v_fila_loterica
  from (
    select
      b.titulo as bolao,
      coalesce(sum(b.valor_aposta_cota_centavos * p.qtd_cotas), 0) as repasse_centavos,
      b.comprovante_url,
      case when b.comprovante_url is null then 'aguardando_comprovante' else b.status end as status
    from mod_sobolao.tbl_sbl_boloes b
    left join mod_sobolao.tbl_sbl_participacoes p on p.id_bolao = b.cod_bolao and p.status in ('pago','confirmado')
    where b.status in ('aberto','fechando','registrado')
    group by b.cod_bolao
    order by b.data_limite
    limit 40
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.atualizado_em desc), '[]'::jsonb)
    into v_chamados
  from (
    select cod_chamado, assunto, prioridade, status, atualizado_em
    from mod_sobolao.tbl_sbl_chamados
    where status in ('aberto','em_atendimento','respondido')
    order by atualizado_em desc
    limit 80
  ) s;

  select coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb)
    into v_fila_admin
  from (
    select 1::bigint as id, 'bolao' as tipo, 'Boloes aguardando comprovante' as titulo, 'Admin' as responsavel, 0::bigint as valor_centavos, 'pendente' as status
    where exists (select 1 from mod_sobolao.tbl_sbl_boloes b where b.status = 'registrado' and b.comprovante_url is null)
    union all
    select 2::bigint, 'loterica', 'Lotericas em analise', 'Suporte', 0::bigint, 'analise'
    where exists (select 1 from mod_sobolao.tbl_sbl_lotericas l where l.status = 'analise')
    union all
    select 3::bigint, 'suporte', 'Chamados abertos', 'Suporte', 0::bigint, 'pendente'
    where exists (select 1 from mod_sobolao.tbl_sbl_chamados c where c.status in ('aberto','em_atendimento'))
  ) s;

  return (v_base || jsonb_build_object(
    'ok', true,
    'lotericas', v_lotericas,
    'fila_loterica', v_fila_loterica,
    'chamados', v_chamados,
    'fila_admin', v_fila_admin
  ));
end;
$$;

create or replace function public.sobolao_loterica_painel_rpc(p_cnpj text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_admin boolean := mod_sobolao.fn_sbl_admin_ok('acessar');
  v_cnpj text := nullif(regexp_replace(coalesce(p_cnpj, ''), '[^0-9]', '', 'g'), '');
  v_loterica bigint;
  v_result jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;

  select l.cod_loterica
    into v_loterica
  from mod_sobolao.tbl_sbl_lotericas l
  where (v_cnpj is null or l.cnpj = v_cnpj)
    and (
      v_admin
      or exists (
        select 1
        from mod_sobolao.tbl_sbl_loterica_usuarios lu
        where lu.id_loterica = l.cod_loterica
          and lu.uid_usuario = v_uid
          and lu.ativo
      )
    )
  order by case when l.status = 'ativa' then 0 else 1 end, l.nome
  limit 1;

  if v_loterica is null then
    return jsonb_build_object('ok', false, 'error', 'sem_loterica_vinculada');
  end if;

  if v_admin then
    v_result := public.adm_sobolao_painel_rpc(null);
    if coalesce((v_result ->> 'ok')::boolean, false) then
      return v_result;
    end if;
  end if;

  select jsonb_build_object(
    'ok', true,
    'resumo', jsonb_build_object(
      'boloes_ativos', (select count(*) from mod_sobolao.tbl_sbl_boloes b where b.id_loterica = v_loterica and b.status in ('aberto','fechando','registrado')),
      'cotas_reservadas', coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p join mod_sobolao.tbl_sbl_boloes b on b.cod_bolao = p.id_bolao where b.id_loterica = v_loterica and p.status in ('reservado','pago','confirmado','premiado')), 0),
      'premios_centavos', 0,
      'gestao_centavos', 0,
      'parceiras', 1,
      'pendencias', coalesce((select count(*) from mod_sobolao.tbl_sbl_boloes b where b.id_loterica = v_loterica and b.status = 'registrado' and b.comprovante_url is null), 0),
      'taxa_gestao_percentual', 10,
      'conversao_alvo_percentual', 30,
      'apostas_media_mes', 4,
      'ticket_oficial_centavos', 600
    ),
    'fluxo', jsonb_build_array(
      jsonb_build_object('titulo','Formacao','texto','Bolao aberto com cotas, modalidade, concurso e limite definidos.'),
      jsonb_build_object('titulo','Repasse','texto','Valor oficial segue para a loterica parceira; taxa fica separada.'),
      jsonb_build_object('titulo','Documento','texto','Comprovante da aposta e auditoria ficam vinculados ao bolao.'),
      jsonb_build_object('titulo','Apuracao','texto','Resultado, premio e rateio proporcional sao registrados.')
    ),
    'modalidades', (select coalesce(jsonb_agg(jsonb_build_object('chave', chave, 'nome', nome) order by nome), '[]'::jsonb) from mod_sobolao.tbl_sbl_modalidades where ativo),
    'lotericas', (
      select coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb)
      from (
        select
          l.cod_loterica,
          l.nome,
          l.cnpj,
          l.cidade,
          l.uf,
          l.whatsapp,
          l.status,
          (select count(*) from mod_sobolao.tbl_sbl_boloes b where b.id_loterica = l.cod_loterica and b.status in ('aberto','fechando','registrado')) as boloes_ativos,
          coalesce((select sum(b.valor_aposta_cota_centavos * p.qtd_cotas)
            from mod_sobolao.tbl_sbl_boloes b
            join mod_sobolao.tbl_sbl_participacoes p on p.id_bolao = b.cod_bolao
            where b.id_loterica = l.cod_loterica and p.status in ('pago','confirmado')), 0) as repasse_pendente_centavos
        from mod_sobolao.tbl_sbl_lotericas l
        where l.cod_loterica = v_loterica
      ) s
    ),
    'boloes', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.data_limite), '[]'::jsonb)
      from (
        select
          b.cod_bolao,
          b.titulo,
          m.nome as modalidade,
          m.chave as modalidade_chave,
          c.numero as concurso,
          c.data_sorteio,
          b.data_limite,
          l.nome as loterica,
          l.cnpj as loterica_cnpj,
          b.qtd_cotas,
          coalesce((select sum(p.qtd_cotas) from mod_sobolao.tbl_sbl_participacoes p where p.id_bolao = b.cod_bolao and p.status in ('reservado','pago','confirmado','premiado')), 0) as cotas_reservadas,
          b.valor_aposta_cota_centavos,
          b.taxa_gestao_percentual,
          (b.valor_aposta_cota_centavos + round(b.valor_aposta_cota_centavos * b.taxa_gestao_percentual / 100.0)::integer) as valor_total_cota_centavos,
          b.status,
          b.numeros_json as numeros,
          b.comprovante_url
        from mod_sobolao.tbl_sbl_boloes b
        join mod_sobolao.tbl_sbl_concursos c on c.cod_concurso = b.id_concurso
        join mod_sobolao.tbl_sbl_modalidades m on m.cod_modalidade = c.id_modalidade
        left join mod_sobolao.tbl_sbl_lotericas l on l.cod_loterica = b.id_loterica
        where b.id_loterica = v_loterica
        order by b.data_limite
        limit 80
      ) s
    ),
    'fila_loterica', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.status, s.bolao), '[]'::jsonb)
      from (
        select
          b.titulo as bolao,
          coalesce(sum(b.valor_aposta_cota_centavos * p.qtd_cotas), 0) as repasse_centavos,
          b.comprovante_url,
          case when b.comprovante_url is null then 'aguardando_comprovante' else b.status end as status
        from mod_sobolao.tbl_sbl_boloes b
        left join mod_sobolao.tbl_sbl_participacoes p on p.id_bolao = b.cod_bolao and p.status in ('pago','confirmado')
        where b.id_loterica = v_loterica
          and b.status in ('aberto','fechando','registrado')
        group by b.cod_bolao
        order by b.data_limite
        limit 40
      ) s
    ),
    'resultados', '[]'::jsonb,
    'premios', '[]'::jsonb,
    'chamados', (
      select coalesce(jsonb_agg(to_jsonb(s) order by s.atualizado_em desc), '[]'::jsonb)
      from (
        select cod_chamado, assunto, prioridade, status, atualizado_em
        from mod_sobolao.tbl_sbl_chamados
        where id_loterica = v_loterica
        order by atualizado_em desc
        limit 30
      ) s
    )
  )
  into v_result;

  if coalesce((v_result ->> 'ok')::boolean, false) then
    return v_result;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.sobolao_participar_rpc(
  p_cod_bolao bigint,
  p_qtd_cotas integer,
  p_palpite_numeros jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_id_usuario bigint;
  v_bolao mod_sobolao.tbl_sbl_boloes%rowtype;
  v_ocupadas integer;
  v_taxa_cota integer;
  v_valor_aposta bigint;
  v_taxa bigint;
  v_total bigint;
  v_participacao bigint;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;
  if coalesce(p_qtd_cotas, 0) <= 0 then
    return jsonb_build_object('ok', false, 'error', 'dados_obrigatorios');
  end if;

  v_id_usuario := mod_sobolao.fn_sbl_usuario_atual();
  if v_id_usuario is null then
    return jsonb_build_object('ok', false, 'error', 'usuario_nao_encontrado');
  end if;

  select *
    into v_bolao
  from mod_sobolao.tbl_sbl_boloes
  where cod_bolao = p_cod_bolao
  for update;

  if not found or v_bolao.status not in ('aberto','fechando') or v_bolao.data_limite < now() then
    return jsonb_build_object('ok', false, 'error', 'bolao_indisponivel');
  end if;

  select coalesce(sum(qtd_cotas), 0)::integer
    into v_ocupadas
  from mod_sobolao.tbl_sbl_participacoes
  where id_bolao = v_bolao.cod_bolao
    and status in ('reservado','pago','confirmado','premiado');

  if v_ocupadas + p_qtd_cotas > v_bolao.qtd_cotas then
    return jsonb_build_object('ok', false, 'error', 'cotas_insuficientes', 'cotas_disponiveis', greatest(v_bolao.qtd_cotas - v_ocupadas, 0));
  end if;

  v_taxa_cota := round(v_bolao.valor_aposta_cota_centavos * v_bolao.taxa_gestao_percentual / 100.0)::integer;
  v_valor_aposta := v_bolao.valor_aposta_cota_centavos::bigint * p_qtd_cotas;
  v_taxa := v_taxa_cota::bigint * p_qtd_cotas;
  v_total := v_valor_aposta + v_taxa;

  insert into mod_sobolao.tbl_sbl_participacoes (
    id_bolao,
    id_usuario,
    qtd_cotas,
    valor_aposta_centavos,
    taxa_gestao_centavos,
    valor_total_centavos,
    status,
    palpite_numeros_json
  )
  values (
    v_bolao.cod_bolao,
    v_id_usuario,
    p_qtd_cotas,
    v_valor_aposta,
    v_taxa,
    v_total,
    'reservado',
    coalesce(p_palpite_numeros, '[]'::jsonb)
  )
  returning cod_participacao into v_participacao;

  insert into mod_sobolao.tbl_sbl_auditoria(uid_usuario, area, acao, alvo_tipo, alvo_id, detalhes_json)
  values (v_uid, 'sobolao', 'participar', 'participacao', v_participacao::text, jsonb_build_object('id_bolao', v_bolao.cod_bolao, 'qtd_cotas', p_qtd_cotas, 'valor_total_centavos', v_total));

  return jsonb_build_object(
    'ok', true,
    'participacao', jsonb_build_object(
      'cod_participacao', v_participacao,
      'id_bolao', v_bolao.cod_bolao,
      'qtd_cotas', p_qtd_cotas,
      'valor_total_centavos', v_total,
      'status', 'reservado'
    )
  );
end;
$$;

create or replace function public.adm_sobolao_loterica_salvar_rpc(
  p_cod_loterica bigint default null,
  p_nome text default null,
  p_cnpj text default null,
  p_cidade text default null,
  p_uf text default null,
  p_whatsapp text default null,
  p_status text default 'analise'
)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_cnpj text := regexp_replace(coalesce(p_cnpj, ''), '[^0-9]', '', 'g');
  v_loterica bigint;
begin
  if not mod_sobolao.fn_sbl_admin_ok('lotericas') then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_sobolao');
  end if;
  if nullif(btrim(coalesce(p_nome, '')), '') is null or v_cnpj !~ '^[0-9]{14}$' then
    return jsonb_build_object('ok', false, 'error', 'dados_obrigatorios');
  end if;

  insert into mod_sobolao.tbl_sbl_lotericas (nome, cnpj, cidade, uf, whatsapp, status)
  values (btrim(p_nome), v_cnpj, nullif(btrim(coalesce(p_cidade, '')), ''), upper(nullif(btrim(coalesce(p_uf, '')), '')), nullif(regexp_replace(coalesce(p_whatsapp, ''), '[^0-9]', '', 'g'), ''), coalesce(nullif(p_status, ''), 'analise'))
  on conflict (cnpj) do update
  set nome = excluded.nome,
      cidade = excluded.cidade,
      uf = excluded.uf,
      whatsapp = excluded.whatsapp,
      status = excluded.status,
      atualizado_em = now()
  returning cod_loterica into v_loterica;

  insert into mod_sobolao.tbl_sbl_auditoria(uid_usuario, area, acao, alvo_tipo, alvo_id, detalhes_json)
  values (v_uid, 'sobolao', 'salvar_loterica', 'loterica', v_loterica::text, jsonb_build_object('cnpj', v_cnpj, 'status', p_status));

  return jsonb_build_object('ok', true, 'cod_loterica', v_loterica);
end;
$$;

create or replace function public.adm_sobolao_bolao_salvar_rpc(
  p_cod_bolao bigint default null,
  p_titulo text default null,
  p_modalidade_chave text default 'mega_sena',
  p_concurso_numero integer default null,
  p_data_sorteio date default null,
  p_loterica_cnpj text default null,
  p_qtd_cotas integer default 100,
  p_valor_aposta_cota_centavos integer default 600,
  p_taxa_gestao_percentual numeric default 10,
  p_data_limite timestamptz default null,
  p_numeros_json jsonb default '[]'::jsonb,
  p_status text default 'rascunho'
)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_chave text := coalesce(nullif(regexp_replace(lower(btrim(coalesce(p_modalidade_chave, 'mega_sena'))), '[^a-z0-9_]+', '_', 'g'), ''), 'mega_sena');
  v_modalidade bigint;
  v_concurso bigint;
  v_loterica bigint;
  v_bolao bigint;
  v_cnpj text := nullif(regexp_replace(coalesce(p_loterica_cnpj, ''), '[^0-9]', '', 'g'), '');
begin
  if not mod_sobolao.fn_sbl_admin_ok('boloes') then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_sobolao');
  end if;
  if nullif(btrim(coalesce(p_titulo, '')), '') is null or coalesce(p_concurso_numero, 0) <= 0 or p_data_sorteio is null or coalesce(p_qtd_cotas, 0) <= 0 or coalesce(p_valor_aposta_cota_centavos, 0) <= 0 or p_data_limite is null then
    return jsonb_build_object('ok', false, 'error', 'dados_obrigatorios');
  end if;

  insert into mod_sobolao.tbl_sbl_modalidades (chave, nome, qtd_numeros, minimo_numero, maximo_numero)
  values (v_chave, initcap(replace(v_chave, '_', ' ')), 6, 1, 60)
  on conflict (chave) do update set ativo = true, atualizado_em = now()
  returning cod_modalidade into v_modalidade;

  insert into mod_sobolao.tbl_sbl_concursos (id_modalidade, numero, data_sorteio, status)
  values (v_modalidade, p_concurso_numero, p_data_sorteio, 'programado')
  on conflict (id_modalidade, numero) do update
  set data_sorteio = excluded.data_sorteio,
      atualizado_em = now()
  returning cod_concurso into v_concurso;

  if v_cnpj is not null then
    select l.cod_loterica into v_loterica
    from mod_sobolao.tbl_sbl_lotericas l
    where l.cnpj = v_cnpj
    limit 1;
  end if;

  if p_cod_bolao is null then
    insert into mod_sobolao.tbl_sbl_boloes (
      id_concurso,
      id_loterica,
      titulo,
      status,
      qtd_cotas,
      valor_aposta_cota_centavos,
      taxa_gestao_percentual,
      data_limite,
      numeros_json,
      criado_por
    )
    values (
      v_concurso,
      v_loterica,
      btrim(p_titulo),
      coalesce(nullif(p_status, ''), 'rascunho'),
      p_qtd_cotas,
      p_valor_aposta_cota_centavos,
      coalesce(p_taxa_gestao_percentual, 10),
      p_data_limite,
      coalesce(p_numeros_json, '[]'::jsonb),
      v_uid
    )
    returning cod_bolao into v_bolao;
  else
    update mod_sobolao.tbl_sbl_boloes
       set id_concurso = v_concurso,
           id_loterica = v_loterica,
           titulo = btrim(p_titulo),
           status = coalesce(nullif(p_status, ''), status),
           qtd_cotas = p_qtd_cotas,
           valor_aposta_cota_centavos = p_valor_aposta_cota_centavos,
           taxa_gestao_percentual = coalesce(p_taxa_gestao_percentual, taxa_gestao_percentual),
           data_limite = p_data_limite,
           numeros_json = coalesce(p_numeros_json, '[]'::jsonb),
           atualizado_em = now()
     where cod_bolao = p_cod_bolao
     returning cod_bolao into v_bolao;

    if v_bolao is null then
      return jsonb_build_object('ok', false, 'error', 'bolao_nao_encontrado');
    end if;
  end if;

  insert into mod_sobolao.tbl_sbl_auditoria(uid_usuario, area, acao, alvo_tipo, alvo_id, detalhes_json)
  values (v_uid, 'sobolao', 'salvar_bolao', 'bolao', v_bolao::text, jsonb_build_object('status', p_status, 'concurso', p_concurso_numero));

  return jsonb_build_object('ok', true, 'cod_bolao', v_bolao);
end;
$$;

create or replace function public.adm_sobolao_status_rpc(
  p_tipo text,
  p_id bigint,
  p_status text,
  p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
begin
  if not mod_sobolao.fn_sbl_admin_ok('acessar') then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_sobolao');
  end if;

  if p_tipo = 'bolao' then
    update mod_sobolao.tbl_sbl_boloes set status = p_status, atualizado_em = now() where cod_bolao = p_id;
  elsif p_tipo = 'loterica' then
    update mod_sobolao.tbl_sbl_lotericas set status = p_status, atualizado_em = now() where cod_loterica = p_id;
  elsif p_tipo = 'participacao' then
    update mod_sobolao.tbl_sbl_participacoes set status = p_status, atualizado_em = now() where cod_participacao = p_id;
  elsif p_tipo = 'chamado' then
    update mod_sobolao.tbl_sbl_chamados set status = p_status, atualizado_em = now(), encerrado_em = case when p_status in ('encerrado','cancelado') then now() else encerrado_em end where cod_chamado = p_id;
  end if;

  insert into mod_sobolao.tbl_sbl_auditoria(uid_usuario, area, acao, alvo_tipo, alvo_id, detalhes_json)
  values (v_uid, 'sobolao', 'atualizar_status', p_tipo, p_id::text, jsonb_build_object('status', p_status, 'observacao', p_observacao));

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.sobolao_suporte_chamado_rpc(
  p_assunto text,
  p_mensagem text,
  p_origem text default 'usuario',
  p_id_bolao bigint default null,
  p_id_loterica bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'mod_sobolao', 'public', 'extensions', 'auth', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_id_usuario bigint;
  v_chamado bigint;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;
  if nullif(btrim(coalesce(p_assunto, '')), '') is null or nullif(btrim(coalesce(p_mensagem, '')), '') is null then
    return jsonb_build_object('ok', false, 'error', 'dados_obrigatorios');
  end if;

  v_id_usuario := mod_sobolao.fn_sbl_usuario_atual();

  insert into mod_sobolao.tbl_sbl_chamados (
    uid_origem,
    id_usuario,
    id_loterica,
    id_bolao,
    origem,
    assunto,
    mensagem,
    mensagens_json
  )
  values (
    v_uid,
    v_id_usuario,
    p_id_loterica,
    p_id_bolao,
    coalesce(nullif(p_origem, ''), 'usuario'),
    btrim(p_assunto),
    btrim(p_mensagem),
    jsonb_build_array(jsonb_build_object('autor', coalesce(nullif(p_origem, ''), 'usuario'), 'mensagem', btrim(p_mensagem), 'criado_em', now()))
  )
  returning cod_chamado into v_chamado;

  return jsonb_build_object('ok', true, 'cod_chamado', v_chamado);
end;
$$;

do $$
declare
  r record;
begin
  for r in
    select unnest(array[
      'tbl_sbl_modalidades',
      'tbl_sbl_lotericas',
      'tbl_sbl_loterica_usuarios',
      'tbl_sbl_concursos',
      'tbl_sbl_boloes',
      'tbl_sbl_participacoes',
      'tbl_sbl_premios',
      'tbl_sbl_rateios',
      'tbl_sbl_documentos',
      'tbl_sbl_chamados',
      'tbl_sbl_auditoria'
    ]) as tabela
  loop
    execute format('alter table mod_sobolao.%I enable row level security', r.tabela);
    if not exists (
      select 1
      from pg_policies
      where schemaname = 'mod_sobolao'
        and tablename = r.tabela
        and policyname = 'turbo_bloqueio_padrao_sem_acesso_direto'
    ) then
      execute format('create policy turbo_bloqueio_padrao_sem_acesso_direto on mod_sobolao.%I using (false) with check (false)', r.tabela);
    end if;
  end loop;
end $$;

grant usage on schema mod_sobolao to service_role;
grant all on all tables in schema mod_sobolao to service_role;
grant all on all sequences in schema mod_sobolao to service_role;
alter default privileges for role postgres in schema mod_sobolao grant all on tables to service_role;
alter default privileges for role postgres in schema mod_sobolao grant all on sequences to service_role;
alter default privileges for role postgres in schema mod_sobolao grant all on functions to service_role;

do $$
declare
  r record;
begin
  for r in
    select p.oid::regprocedure as assinatura
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where (n.nspname = 'public' and p.proname in (
      'sobolao_usuario_painel_rpc',
      'sobolao_loterica_painel_rpc',
      'sobolao_participar_rpc',
      'sobolao_suporte_chamado_rpc',
      'adm_sobolao_painel_rpc',
      'adm_sobolao_loterica_salvar_rpc',
      'adm_sobolao_bolao_salvar_rpc',
      'adm_sobolao_status_rpc'
    ))
    or (n.nspname = 'mod_sobolao')
  loop
    execute format('revoke all on function %s from public', r.assinatura);
    execute format('grant execute on function %s to service_role', r.assinatura);
    if position('public.' in r.assinatura::text) = 1 then
      execute format('grant execute on function %s to authenticated', r.assinatura);
    end if;
  end loop;
end $$;
