-- ATENCAO: este arquivo nao e mais executavel.
--
-- O prototipo MMN anterior foi substituido integralmente pelo sistema
-- versionado e transacional. As fontes oficiais do backend, nesta ordem, sao:
--
--   supabase/migrations/20260801040000_mmn_sistema_completo.sql
--     Governanca, regulamento, regras versionadas e operacao base.
--
--   supabase/migrations/20260801041000_mmn_simuladores_v2.sql
--     Simuladores V2, replay historico, comparacao e exportacao.
--
--   supabase/migrations/20260801042000_mmn_operacional_final.sql
--     RPA, progresso de publicacao, notificacoes, expiracoes, privacidade
--     por capacidade e grants finais.
--
-- Cada migration deve ser aplicada isoladamente, na ordem indicada, com o
-- CLI local do projeto.
-- Nao use `supabase db push`, pois existem outras migrations locais fora
-- do escopo deste modulo.
