-- Turbo Tiger MMN
-- Schema isolado para o modulo de marketing multinivel.
-- Este arquivo e local. Aplique manualmente quando quiser instalar o backend MMN.

begin;

create schema if not exists mod_mmn;

create table if not exists mod_mmn.tbl_mmn_percentuais_nivel (
  cod_mmn_percentual bigint generated by default as identity primary key,
  nivel smallint not null unique check (nivel between 1 and 6),
  percentual numeric(6,3) not null check (percentual >= 0 and percentual <= 33),
  ativo boolean not null default true,
  ordem integer not null default 100,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists mod_mmn.tbl_mmn_ranks (
  cod_mmn_rank bigint generated by default as identity primary key,
  chave text not null unique,
  nome text not null,
  min_ativos_rede integer not null default 0 check (min_ativos_rede >= 0),
  percentual_pool numeric(6,3) not null default 0 check (percentual_pool >= 0 and percentual_pool <= 33),
  ordem integer not null default 100,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists mod_mmn.tbl_mmn_periodos (
  cod_mmn_periodo bigint generated by default as identity primary key,
  periodo date not null unique,
  status text not null default 'aberto'
    check (status in ('aberto', 'apurando', 'fechado', 'pago', 'cancelado')),
  ticket_centavos integer not null default 1990 check (ticket_centavos >= 0),
  payout_teto_percentual numeric(6,3) not null default 33 check (payout_teto_percentual >= 0 and payout_teto_percentual <= 33),
  usuarios_ativos integer not null default 0 check (usuarios_ativos >= 0),
  mrr_centavos bigint not null default 0 check (mrr_centavos >= 0),
  comissao_centavos bigint not null default 0 check (comissao_centavos >= 0),
  bonus_centavos bigint not null default 0 check (bonus_centavos >= 0),
  observacao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  fechado_em timestamptz
);

create table if not exists mod_mmn.tbl_mmn_usuario_status (
  id_usuario bigint primary key references public.tbl_usuarios(cod_usuario) on delete cascade,
  status text not null default 'ativo'
    check (status in ('ativo', 'pendente', 'bloqueado', 'cancelado')),
  rank_chave text references mod_mmn.tbl_mmn_ranks(chave),
  bloqueado_motivo text,
  suporte_observacao text,
  atualizado_por uuid,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists mod_mmn.tbl_mmn_qualificacoes (
  cod_mmn_qualificacao bigint generated by default as identity primary key,
  id_periodo bigint not null references mod_mmn.tbl_mmn_periodos(cod_mmn_periodo) on delete cascade,
  id_usuario bigint not null references public.tbl_usuarios(cod_usuario) on delete cascade,
  diretos_ativos integer not null default 0 check (diretos_ativos >= 0),
  diretos_com_10_ativos integer not null default 0 check (diretos_com_10_ativos >= 0),
  rede_ativos integer not null default 0 check (rede_ativos >= 0),
  qualificado_comissao boolean not null default false,
  qualificado_nivel_5 boolean not null default false,
  qualificado_nivel_6 boolean not null default false,
  rank_chave text references mod_mmn.tbl_mmn_ranks(chave),
  detalhes_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_periodo, id_usuario)
);

create table if not exists mod_mmn.tbl_mmn_lancamentos (
  cod_mmn_lancamento bigint generated by default as identity primary key,
  id_periodo bigint not null references mod_mmn.tbl_mmn_periodos(cod_mmn_periodo) on delete cascade,
  id_usuario_beneficiario bigint not null references public.tbl_usuarios(cod_usuario) on delete cascade,
  id_usuario_origem bigint references public.tbl_usuarios(cod_usuario) on delete set null,
  nivel smallint check (nivel between 1 and 6),
  tipo text not null default 'comissao'
    check (tipo in ('comissao', 'bonus_lideranca', 'premiacao', 'ajuste', 'estorno')),
  status text not null default 'pendente'
    check (status in ('pendente', 'confirmado', 'retido', 'pago', 'cancelado')),
  base_centavos bigint not null default 0 check (base_centavos >= 0),
  percentual numeric(6,3) not null default 0 check (percentual >= 0 and percentual <= 33),
  valor_centavos bigint not null default 0 check (valor_centavos >= 0),
  origem_ref text,
  detalhes_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists mod_mmn.tbl_mmn_premios (
  cod_mmn_premio bigint generated by default as identity primary key,
  chave text not null unique,
  nome text not null,
  descricao text,
  rank_chave text references mod_mmn.tbl_mmn_ranks(chave),
  valor_centavos bigint check (valor_centavos is null or valor_centavos >= 0),
  percentual_pool numeric(6,3) check (percentual_pool is null or (percentual_pool >= 0 and percentual_pool <= 33)),
  ativo boolean not null default true,
  ordem integer not null default 100,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists mod_mmn.tbl_mmn_suporte_ocorrencias (
  cod_mmn_ocorrencia bigint generated by default as identity primary key,
  id_usuario bigint not null references public.tbl_usuarios(cod_usuario) on delete cascade,
  tipo text not null default 'duvida',
  status text not null default 'aberta'
    check (status in ('aberta', 'em_atendimento', 'resolvida', 'cancelada')),
  prioridade text not null default 'normal'
    check (prioridade in ('baixa', 'normal', 'alta', 'critica')),
  assunto text not null,
  detalhe text,
  criado_por uuid,
  atendido_por uuid,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  resolvido_em timestamptz
);

create table if not exists mod_mmn.tbl_mmn_auditoria (
  cod_mmn_auditoria bigint generated by default as identity primary key,
  id_usuario bigint references public.tbl_usuarios(cod_usuario) on delete set null,
  uid_admin uuid,
  area text not null default 'mmn',
  acao text not null,
  alvo_tipo text,
  alvo_id text,
  detalhes_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists ix_mmn_lancamentos_beneficiario_periodo
  on mod_mmn.tbl_mmn_lancamentos(id_usuario_beneficiario, id_periodo, status);

create index if not exists ix_mmn_lancamentos_origem
  on mod_mmn.tbl_mmn_lancamentos(id_usuario_origem, nivel);

create unique index if not exists ux_mmn_lancamentos_unico
  on mod_mmn.tbl_mmn_lancamentos(
    id_periodo,
    id_usuario_beneficiario,
    (coalesce(id_usuario_origem, 0)),
    (coalesce(nivel, 0)),
    tipo,
    (coalesce(origem_ref, ''))
  );

create index if not exists ix_mmn_qualificacoes_usuario_periodo
  on mod_mmn.tbl_mmn_qualificacoes(id_usuario, id_periodo);

create index if not exists ix_mmn_suporte_usuario_status
  on mod_mmn.tbl_mmn_suporte_ocorrencias(id_usuario, status, criado_em desc);

alter table mod_mmn.tbl_mmn_percentuais_nivel enable row level security;
alter table mod_mmn.tbl_mmn_ranks enable row level security;
alter table mod_mmn.tbl_mmn_periodos enable row level security;
alter table mod_mmn.tbl_mmn_usuario_status enable row level security;
alter table mod_mmn.tbl_mmn_qualificacoes enable row level security;
alter table mod_mmn.tbl_mmn_lancamentos enable row level security;
alter table mod_mmn.tbl_mmn_premios enable row level security;
alter table mod_mmn.tbl_mmn_suporte_ocorrencias enable row level security;
alter table mod_mmn.tbl_mmn_auditoria enable row level security;

insert into mod_mmn.tbl_mmn_percentuais_nivel(nivel, percentual, ordem)
values
  (1, 10.700, 10),
  (2, 8.000, 20),
  (3, 7.600, 30),
  (4, 3.800, 40),
  (5, 1.900, 50),
  (6, 1.000, 60)
on conflict (nivel) do update
set percentual = excluded.percentual,
    ordem = excluded.ordem,
    ativo = true,
    atualizado_em = now();

insert into mod_mmn.tbl_mmn_ranks(chave, nome, min_ativos_rede, percentual_pool, ordem)
values
  ('executivo', 'Executivo', 1000, 2.000, 10),
  ('senior', 'Senior', 5000, 4.000, 20),
  ('master', 'Master', 10000, 6.000, 30),
  ('elite', 'Elite', 50000, 8.000, 40)
on conflict (chave) do update
set nome = excluded.nome,
    min_ativos_rede = excluded.min_ativos_rede,
    percentual_pool = excluded.percentual_pool,
    ordem = excluded.ordem,
    ativo = true,
    atualizado_em = now();

insert into mod_mmn.tbl_mmn_premios(chave, nome, descricao, rank_chave, percentual_pool, ordem)
values
  ('bonus_lideranca_executivo', 'Bonus Lideranca Executivo', 'Pool de lideranca para redes com 1.000 ativos.', 'executivo', 2.000, 10),
  ('bonus_lideranca_senior', 'Bonus Lideranca Senior', 'Pool de lideranca para redes com 5.000 ativos.', 'senior', 4.000, 20),
  ('bonus_lideranca_master', 'Bonus Lideranca Master', 'Pool de lideranca para redes com 10.000 ativos.', 'master', 6.000, 30),
  ('bonus_lideranca_elite', 'Bonus Lideranca Elite', 'Pool de lideranca para redes com 50.000 ativos.', 'elite', 8.000, 40)
on conflict (chave) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    rank_chave = excluded.rank_chave,
    percentual_pool = excluded.percentual_pool,
    ordem = excluded.ordem,
    ativo = true,
    atualizado_em = now();

insert into mod_admin.tbl_adm_areas(chave, nome, descricao, ativo, ordem)
values ('mmn', 'MMN', 'Marketing multinivel, indicacoes, comissoes, bonificacoes e premiacoes.', true, 30)
on conflict (chave) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    ativo = true,
    ordem = excluded.ordem,
    atualizado_em = now();

insert into mod_admin.tbl_adm_perfis(chave, nome, descricao, permissoes_json, ativo)
values (
  'mmn_suporte',
  'Suporte MMN',
  'Equipe de suporte para acompanhamento de rede, indicacoes e ocorrencias MMN.',
  jsonb_build_object(
    'areas', jsonb_build_array('mmn'),
    'mmn', jsonb_build_object('acessar', true, 'suporte', true, 'configurar', false, 'pagar', false)
  ),
  true
)
on conflict (chave) do update
set nome = excluded.nome,
    descricao = excluded.descricao,
    permissoes_json = excluded.permissoes_json,
    ativo = true,
    atualizado_em = now();

update mod_admin.tbl_adm_perfis
set permissoes_json =
  case
    when chave = 'super_admin' then
      permissoes_json ||
      jsonb_build_object(
        'mmn', jsonb_build_object('acessar', true, 'configurar', true, 'pagar', true, 'suporte', true),
        'areas', (
          select jsonb_agg(distinct area.chave order by area.chave)
          from jsonb_array_elements_text(coalesce(permissoes_json->'areas', '[]'::jsonb) || '["mmn"]'::jsonb) as area(chave)
        )
      )
    else permissoes_json
  end,
  atualizado_em = now()
where chave = 'super_admin';

create or replace function mod_mmn.fn_periodo_mes(p_data date default current_date)
returns date
language sql
stable
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  select date_trunc('month', coalesce(p_data, current_date))::date;
$$;

create or replace function mod_mmn.fn_centavos(p_valor numeric)
returns bigint
language sql
immutable
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  select greatest(0, round(coalesce(p_valor, 0) * 100)::bigint);
$$;

create or replace function mod_mmn.fn_admin_tem_acesso(p_acao text default 'acessar')
returns boolean
language plpgsql
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
begin
  if auth.uid() is null then
    return false;
  end if;

  return coalesce(public.adm_usuario_tem_area_uid_rpc(auth.uid(), 'mmn', coalesce(p_acao, 'acessar')), false)
      or coalesce(public.adm_usuario_tem_area_uid_rpc(auth.uid(), 'admin', 'acessar'), false);
end;
$$;

create or replace function mod_mmn.fn_usuario_auth()
returns bigint
language sql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  select u.cod_usuario
  from public.tbl_usuarios u
  where u.uid_usuario = auth.uid()
  limit 1;
$$;

create or replace function mod_mmn.fn_usuario_ativo(p_usuario public.tbl_usuarios)
returns boolean
language sql
stable
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  select
    p_usuario.cod_usuario is not null
    and coalesce((select s.status from mod_mmn.tbl_mmn_usuario_status s where s.id_usuario = p_usuario.cod_usuario), 'ativo') = 'ativo'
    and (
      public.turbotiger_normalizar_licenca(coalesce(p_usuario.licenca, 'trial')) in ('0', 'free')
      or p_usuario.validade is null
      or p_usuario.validade >= current_date
    );
$$;

create or replace function mod_mmn.fn_linha_acima(p_cod_usuario bigint, p_limite integer default 6)
returns table (
  nivel integer,
  cod_usuario bigint,
  login text,
  nome text,
  rank text
)
language sql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  with recursive acima as (
    select
      1 as nivel,
      ind.cod_usuario,
      ind.loginuser,
      btrim(concat_ws(' ', ind.nomeuser, ind.sobrenome)) as nome,
      ind.id_indicador,
      array[p_cod_usuario, ind.cod_usuario]::bigint[] as caminho
    from public.tbl_usuarios u
    join public.tbl_usuarios ind on ind.cod_usuario = u.id_indicador
    where u.cod_usuario = p_cod_usuario
      and ind.cod_usuario <> u.cod_usuario

    union all

    select
      a.nivel + 1,
      ind.cod_usuario,
      ind.loginuser,
      btrim(concat_ws(' ', ind.nomeuser, ind.sobrenome)) as nome,
      ind.id_indicador,
      a.caminho || ind.cod_usuario
    from acima a
    join public.tbl_usuarios atual on atual.cod_usuario = a.cod_usuario
    join public.tbl_usuarios ind on ind.cod_usuario = atual.id_indicador
    where a.nivel < least(greatest(coalesce(p_limite, 6), 1), 6)
      and ind.cod_usuario <> all(a.caminho)
  ),
  ultimo_rank as (
    select distinct on (q.id_usuario)
      q.id_usuario,
      q.rank_chave
    from mod_mmn.tbl_mmn_qualificacoes q
    join mod_mmn.tbl_mmn_periodos p on p.cod_mmn_periodo = q.id_periodo
    order by q.id_usuario, p.periodo desc
  )
  select
    a.nivel,
    a.cod_usuario,
    a.loginuser,
    a.nome,
    coalesce(r.nome, 'Base') as rank
  from acima a
  left join ultimo_rank ur on ur.id_usuario = a.cod_usuario
  left join mod_mmn.tbl_mmn_ranks r on r.chave = ur.rank_chave
  order by a.nivel
  limit least(greatest(coalesce(p_limite, 6), 1), 6);
$$;

create or replace function mod_mmn.fn_linha_abaixo(p_cod_usuario bigint, p_limite integer default 6)
returns table (
  nivel integer,
  cod_usuario bigint,
  login text,
  nome text,
  rank text,
  ativos integer
)
language sql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  with recursive abaixo as (
    select
      1 as nivel,
      u.cod_usuario,
      u.loginuser,
      btrim(concat_ws(' ', u.nomeuser, u.sobrenome)) as nome,
      u.criado_em,
      array[p_cod_usuario, u.cod_usuario]::bigint[] as caminho
    from public.tbl_usuarios u
    where u.id_indicador = p_cod_usuario
      and u.cod_usuario <> p_cod_usuario

    union all

    select
      a.nivel + 1,
      u.cod_usuario,
      u.loginuser,
      btrim(concat_ws(' ', u.nomeuser, u.sobrenome)) as nome,
      u.criado_em,
      a.caminho || u.cod_usuario
    from abaixo a
    join public.tbl_usuarios u on u.id_indicador = a.cod_usuario
    where a.nivel < least(greatest(coalesce(p_limite, 6), 1), 6)
      and u.cod_usuario <> all(a.caminho)
  ),
  resumido as (
    select
      a.*,
      row_number() over (partition by a.nivel order by a.criado_em, a.cod_usuario) as rn
    from abaixo a
  ),
  ultimo_rank as (
    select distinct on (q.id_usuario)
      q.id_usuario,
      q.rank_chave,
      q.rede_ativos
    from mod_mmn.tbl_mmn_qualificacoes q
    join mod_mmn.tbl_mmn_periodos p on p.cod_mmn_periodo = q.id_periodo
    order by q.id_usuario, p.periodo desc
  )
  select
    r.nivel,
    r.cod_usuario,
    r.loginuser,
    r.nome,
    coalesce(rank.nome, 'Base') as rank,
    coalesce(ur.rede_ativos, 0) as ativos
  from resumido r
  left join ultimo_rank ur on ur.id_usuario = r.cod_usuario
  left join mod_mmn.tbl_mmn_ranks rank on rank.chave = ur.rank_chave
  where r.rn = 1
  order by r.nivel
  limit least(greatest(coalesce(p_limite, 6), 1), 6);
$$;

create or replace function mod_mmn.fn_rede_ativos_usuario(p_cod_usuario bigint)
returns integer
language sql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  with recursive rede as (
    select
      u.cod_usuario,
      array[p_cod_usuario, u.cod_usuario]::bigint[] as caminho
    from public.tbl_usuarios u
    where u.id_indicador = p_cod_usuario
      and u.cod_usuario <> p_cod_usuario

    union all

    select
      u.cod_usuario,
      r.caminho || u.cod_usuario
    from rede r
    join public.tbl_usuarios u on u.id_indicador = r.cod_usuario
    where array_length(r.caminho, 1) < 512
      and u.cod_usuario <> all(r.caminho)
  )
  select count(*)::integer
  from rede r
  join public.tbl_usuarios u on u.cod_usuario = r.cod_usuario
  where mod_mmn.fn_usuario_ativo(u);
$$;

create or replace function mod_mmn.fn_diretos_usuario(p_cod_usuario bigint)
returns jsonb
language sql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
  with ultimo_rank as (
    select distinct on (q.id_usuario)
      q.id_usuario,
      q.rank_chave,
      q.rede_ativos
    from mod_mmn.tbl_mmn_qualificacoes q
    join mod_mmn.tbl_mmn_periodos p on p.cod_mmn_periodo = q.id_periodo
    order by q.id_usuario, p.periodo desc
  )
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'cod_usuario', u.cod_usuario,
      'login', u.loginuser,
      'nome', btrim(concat_ws(' ', u.nomeuser, u.sobrenome)),
      'rank', coalesce(r.nome, 'Base'),
      'redeAtivos', coalesce(ur.rede_ativos, 0),
      'status', coalesce(s.status, 'ativo')
    )
    order by u.criado_em desc
  ), '[]'::jsonb)
  from public.tbl_usuarios u
  left join mod_mmn.tbl_mmn_usuario_status s on s.id_usuario = u.cod_usuario
  left join ultimo_rank ur on ur.id_usuario = u.cod_usuario
  left join mod_mmn.tbl_mmn_ranks r on r.chave = ur.rank_chave
  where u.id_indicador = p_cod_usuario
    and u.cod_usuario <> p_cod_usuario;
$$;

create or replace function mod_mmn.fn_rede_usuario_json(p_cod_usuario bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
declare
  v_usuario public.tbl_usuarios%rowtype;
  v_ref text;
  v_qual record;
  v_diretos_ativos integer := 0;
  v_rede_ativos integer := 0;
  v_acima jsonb := '[]'::jsonb;
  v_abaixo jsonb := '[]'::jsonb;
begin
  select *
    into v_usuario
  from public.tbl_usuarios
  where cod_usuario = p_cod_usuario
  limit 1;

  if not found then
    return '{}'::jsonb;
  end if;

  select c.ref
    into v_ref
  from public.tbl_convites_indicacao c
  where c.id_indicador = p_cod_usuario
    and c.ativo
    and (c.expira_em is null or c.expira_em > now())
  order by c.criado_em desc
  limit 1;

  select q.*, r.nome as rank_nome
    into v_qual
  from mod_mmn.tbl_mmn_qualificacoes q
  join mod_mmn.tbl_mmn_periodos p on p.cod_mmn_periodo = q.id_periodo
  left join mod_mmn.tbl_mmn_ranks r on r.chave = q.rank_chave
  where q.id_usuario = p_cod_usuario
  order by p.periodo desc
  limit 1;

  select count(*)::integer
    into v_diretos_ativos
  from public.tbl_usuarios d
  where d.id_indicador = p_cod_usuario
    and d.cod_usuario <> p_cod_usuario
    and mod_mmn.fn_usuario_ativo(d);

  v_rede_ativos := mod_mmn.fn_rede_ativos_usuario(p_cod_usuario);

  select coalesce(jsonb_agg(to_jsonb(x) order by x.nivel), '[]'::jsonb)
    into v_acima
  from mod_mmn.fn_linha_acima(p_cod_usuario, 6) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.nivel), '[]'::jsonb)
    into v_abaixo
  from mod_mmn.fn_linha_abaixo(p_cod_usuario, 6) x;

  return jsonb_build_object(
    'usuario', jsonb_build_object(
      'cod_usuario', v_usuario.cod_usuario,
      'login', v_usuario.loginuser,
      'nome', btrim(concat_ws(' ', v_usuario.nomeuser, v_usuario.sobrenome)),
      'diretos', coalesce(v_qual.diretos_ativos, v_diretos_ativos, 0),
      'redeAtivos', coalesce(v_qual.rede_ativos, v_rede_ativos, 0),
      'rank', coalesce(v_qual.rank_nome, 'Base'),
      'status', coalesce((select s.status from mod_mmn.tbl_mmn_usuario_status s where s.id_usuario = p_cod_usuario), 'ativo'),
      'ref', coalesce(v_ref, '')
    ),
    'acima', v_acima,
    'abaixo', v_abaixo,
    'diretos', mod_mmn.fn_diretos_usuario(p_cod_usuario),
    'convite_link', case when coalesce(v_ref, '') <> '' then 'https://www.turbotiger.com.br/convite/?ref=' || v_ref else '' end
  );
end;
$$;

create or replace function public.mmn_usuario_painel_rpc()
returns jsonb
language plpgsql
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
declare
  v_cod_usuario bigint := mod_mmn.fn_usuario_auth();
  v_periodo date := mod_mmn.fn_periodo_mes(current_date);
  v_periodo_id bigint;
  v_ticket numeric := 19.90;
  v_rede jsonb := '{}'::jsonb;
  v_comissoes jsonb := '[]'::jsonb;
  v_premios jsonb := '[]'::jsonb;
  v_usuarios jsonb := '[]'::jsonb;
  v_confirmado numeric := 0;
  v_pendente numeric := 0;
  v_retido numeric := 0;
  v_rede_ativos integer := 0;
begin
  if v_cod_usuario is null then
    return jsonb_build_object('ok', false, 'error', 'usuario_nao_encontrado');
  end if;

  select cod_mmn_periodo
    into v_periodo_id
  from mod_mmn.tbl_mmn_periodos
  where periodo = v_periodo
  limit 1;

  v_rede := mod_mmn.fn_rede_usuario_json(v_cod_usuario);
  v_rede_ativos := coalesce(nullif(v_rede->'usuario'->>'redeAtivos', '')::integer, 0);

  if v_periodo_id is not null then
    select
      coalesce(sum(valor_centavos) filter (where status in ('confirmado', 'pago')), 0)::numeric / 100,
      coalesce(sum(valor_centavos) filter (where status = 'pendente'), 0)::numeric / 100,
      coalesce(sum(valor_centavos) filter (where status = 'retido'), 0)::numeric / 100
      into v_confirmado, v_pendente, v_retido
    from mod_mmn.tbl_mmn_lancamentos
    where id_periodo = v_periodo_id
      and id_usuario_beneficiario = v_cod_usuario;

    select coalesce(jsonb_agg(item order by ordem desc), '[]'::jsonb)
      into v_comissoes
    from (
      select
        l.criado_em as ordem,
        jsonb_build_object(
          'periodo', to_char(v_periodo, 'YYYY-MM'),
          'beneficiario', ub.loginuser,
          'origem', coalesce(uo.loginuser, ''),
          'nivel', l.nivel,
          'base', l.base_centavos::numeric / 100,
          'percentual', l.percentual,
          'valor', l.valor_centavos::numeric / 100,
          'status', l.status
        ) as item
      from mod_mmn.tbl_mmn_lancamentos l
      join public.tbl_usuarios ub on ub.cod_usuario = l.id_usuario_beneficiario
      left join public.tbl_usuarios uo on uo.cod_usuario = l.id_usuario_origem
      where l.id_periodo = v_periodo_id
        and l.id_usuario_beneficiario = v_cod_usuario
      order by l.criado_em desc
      limit 80
    ) x;
  end if;

  select coalesce(jsonb_agg(item), '[]'::jsonb)
    into v_premios
  from (
    select jsonb_build_object(
      'titulo', p.nome,
      'valor', coalesce(p.valor_centavos, 0)::numeric / 100,
      'status', 'previsto',
      'descricao', coalesce(p.descricao, '')
    ) as item
    from mod_mmn.tbl_mmn_premios p
    where p.ativo
    order by p.ordem
    limit 4
  ) premios;

  v_usuarios := jsonb_build_array(v_rede->'usuario') || coalesce(v_rede->'diretos', '[]'::jsonb);

  return jsonb_build_object(
    'ok', true,
    'resumo', jsonb_build_object(
      'ativos', greatest(v_rede_ativos, 1),
      'mrr', greatest(v_rede_ativos, 1) * v_ticket,
      'payout', case when greatest(v_rede_ativos, 1) * v_ticket > 0 then round(((v_confirmado + v_pendente + v_retido) / (greatest(v_rede_ativos, 1) * v_ticket)) * 100, 2) else 0 end,
      'comissoes', v_confirmado + v_pendente + v_retido,
      'bonificacoes', 0,
      'pendencias', (select count(*) from mod_mmn.tbl_mmn_lancamentos where id_usuario_beneficiario = v_cod_usuario and status in ('pendente', 'retido')),
      'ticket', v_ticket,
      'payoutCap', 33,
      'niveis', 6,
      'margem', 100 - case when greatest(v_rede_ativos, 1) * v_ticket > 0 then round(((v_confirmado + v_pendente + v_retido) / (greatest(v_rede_ativos, 1) * v_ticket)) * 100, 2) else 0 end
    ),
    'usuarios', v_usuarios,
    'rede', v_rede,
    'comissoes', v_comissoes,
    'premios', v_premios,
    'ranks', (select coalesce(jsonb_agg(jsonb_build_object('rank', nome, 'criterio', min_ativos_rede || ' ativos na rede', 'pool', percentual_pool || '%') order by ordem), '[]'::jsonb) from mod_mmn.tbl_mmn_ranks where ativo),
    'regras', jsonb_build_object(
      'levels', (select coalesce(jsonb_agg(jsonb_build_object('nivel', nivel, 'percentual', percentual) order by ordem), '[]'::jsonb) from mod_mmn.tbl_mmn_percentuais_nivel where ativo),
      'qualificacao', jsonb_build_array(
        jsonb_build_object('titulo', 'Diretos ativos', 'texto', 'Minimo de 3 diretos ativos para habilitar comissao.'),
        jsonb_build_object('titulo', 'Niveis 5 e 6', 'texto', 'Exigem continuidade e diretos com rede ativa validada.'),
        jsonb_build_object('titulo', 'Payout', 'texto', 'Teto operacional de 33% sobre receita confirmada.')
      )
    )
  );
end;
$$;

create or replace function public.adm_mmn_painel_rpc(p_periodo date default null)
returns jsonb
language plpgsql
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
declare
  v_periodo date := mod_mmn.fn_periodo_mes(coalesce(p_periodo, current_date));
  v_periodo_id bigint;
  v_ticket numeric := 19.90;
  v_usuarios_ativos integer;
  v_mrr numeric;
  v_comissoes numeric := 0;
  v_bonus numeric := 0;
  v_pendencias integer := 0;
  v_usuarios jsonb := '[]'::jsonb;
  v_rede jsonb := '{}'::jsonb;
begin
  if not mod_mmn.fn_admin_tem_acesso('acessar') then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_mmn');
  end if;

  select cod_mmn_periodo
    into v_periodo_id
  from mod_mmn.tbl_mmn_periodos
  where periodo = v_periodo
  limit 1;

  select count(*)
    into v_usuarios_ativos
  from public.tbl_usuarios u
  where mod_mmn.fn_usuario_ativo(u);

  v_mrr := coalesce(v_usuarios_ativos, 0) * v_ticket;

  if v_periodo_id is not null then
    select
      coalesce(sum(valor_centavos) filter (where tipo = 'comissao'), 0)::numeric / 100,
      coalesce(sum(valor_centavos) filter (where tipo in ('bonus_lideranca', 'premiacao')), 0)::numeric / 100,
      count(*) filter (where status in ('pendente', 'retido'))
      into v_comissoes, v_bonus, v_pendencias
    from mod_mmn.tbl_mmn_lancamentos
    where id_periodo = v_periodo_id;
  end if;

  select coalesce(jsonb_agg(item order by rede_ativos desc, cod_usuario), '[]'::jsonb)
    into v_usuarios
  from (
    select
      u.cod_usuario,
      coalesce(q.rede_ativos, calc.rede_ativos, 0) as rede_ativos,
      jsonb_build_object(
        'cod_usuario', u.cod_usuario,
        'login', u.loginuser,
        'nome', btrim(concat_ws(' ', u.nomeuser, u.sobrenome)),
        'indicador', coalesce(ind.loginuser, ''),
        'diretos', coalesce(q.diretos_ativos, calc.diretos_ativos, 0),
        'redeAtivos', coalesce(q.rede_ativos, calc.rede_ativos, 0),
        'rank', coalesce(r.nome, 'Base'),
        'status', coalesce(s.status, 'ativo'),
        'ref', coalesce(c.ref, '')
      ) as item
    from public.tbl_usuarios u
    left join public.tbl_usuarios ind on ind.cod_usuario = u.id_indicador and ind.cod_usuario <> u.cod_usuario
    left join mod_mmn.tbl_mmn_usuario_status s on s.id_usuario = u.cod_usuario
    left join lateral (
      select q.*
      from mod_mmn.tbl_mmn_qualificacoes q
      join mod_mmn.tbl_mmn_periodos p on p.cod_mmn_periodo = q.id_periodo
      where q.id_usuario = u.cod_usuario
      order by p.periodo desc
      limit 1
    ) q on true
    left join lateral (
      select
        (select count(*)::integer
         from public.tbl_usuarios d
         where d.id_indicador = u.cod_usuario
           and d.cod_usuario <> u.cod_usuario
           and mod_mmn.fn_usuario_ativo(d)) as diretos_ativos,
        mod_mmn.fn_rede_ativos_usuario(u.cod_usuario) as rede_ativos
    ) calc on true
    left join mod_mmn.tbl_mmn_ranks r on r.chave = q.rank_chave
    left join lateral (
      select c.ref
      from public.tbl_convites_indicacao c
      where c.id_indicador = u.cod_usuario
        and c.ativo
        and (c.expira_em is null or c.expira_em > now())
      order by c.criado_em desc
      limit 1
    ) c on true
    order by coalesce(q.rede_ativos, calc.rede_ativos, 0) desc, u.cod_usuario
    limit 120
  ) x;

  select mod_mmn.fn_rede_usuario_json((v_usuarios->0->>'cod_usuario')::bigint)
    into v_rede
  where jsonb_array_length(v_usuarios) > 0;

  return jsonb_build_object(
    'ok', true,
    'resumo', jsonb_build_object(
      'ativos', v_usuarios_ativos,
      'mrr', v_mrr,
      'payout', case when v_mrr > 0 then round(((v_comissoes + v_bonus) / v_mrr) * 100, 2) else 0 end,
      'comissoes', v_comissoes,
      'bonificacoes', v_bonus,
      'pendencias', v_pendencias,
      'ticket', v_ticket,
      'payoutCap', 33,
      'niveis', 6,
      'margem', case when v_mrr > 0 then round(((v_mrr - v_comissoes - v_bonus) / v_mrr) * 100, 2) else 100 end
    ),
    'usuarios', v_usuarios,
    'rede', coalesce(v_rede, '{}'::jsonb),
    'comissoes', (
      select coalesce(jsonb_agg(item order by ordem desc), '[]'::jsonb)
      from (
        select
          l.criado_em as ordem,
          jsonb_build_object(
            'periodo', to_char(v_periodo, 'YYYY-MM'),
            'beneficiario', ub.loginuser,
            'origem', coalesce(uo.loginuser, ''),
            'nivel', l.nivel,
            'base', l.base_centavos::numeric / 100,
            'percentual', l.percentual,
            'valor', l.valor_centavos::numeric / 100,
            'status', l.status
          ) as item
        from mod_mmn.tbl_mmn_lancamentos l
        join public.tbl_usuarios ub on ub.cod_usuario = l.id_usuario_beneficiario
        left join public.tbl_usuarios uo on uo.cod_usuario = l.id_usuario_origem
        where v_periodo_id is not null
          and l.id_periodo = v_periodo_id
        order by l.criado_em desc
        limit 120
      ) lanc
    ),
    'premios', (
      select coalesce(jsonb_agg(jsonb_build_object('titulo', nome, 'valor', coalesce(valor_centavos, 0)::numeric / 100, 'status', 'previsto', 'descricao', coalesce(descricao, '')) order by ordem), '[]'::jsonb)
      from mod_mmn.tbl_mmn_premios
      where ativo
    ),
    'ranks', (
      select coalesce(jsonb_agg(jsonb_build_object('rank', nome, 'criterio', min_ativos_rede || ' ativos na rede', 'pool', percentual_pool || '%') order by ordem), '[]'::jsonb)
      from mod_mmn.tbl_mmn_ranks
      where ativo
    ),
    'regras', jsonb_build_object(
      'levels', (select coalesce(jsonb_agg(jsonb_build_object('nivel', nivel, 'percentual', percentual) order by ordem), '[]'::jsonb) from mod_mmn.tbl_mmn_percentuais_nivel where ativo),
      'qualificacao', jsonb_build_array(
        jsonb_build_object('titulo', 'Diretos ativos', 'texto', 'Minimo de 3 diretos ativos para habilitar comissao.'),
        jsonb_build_object('titulo', 'Base ativa', 'texto', 'Calculo considera base liquida ativa, nao historico bruto.'),
        jsonb_build_object('titulo', 'Payout', 'texto', 'Teto operacional de 33% sobre receita confirmada.')
      )
    )
  );
end;
$$;

create or replace function public.adm_mmn_rede_usuario_rpc(p_cod_usuario bigint)
returns jsonb
language plpgsql
security definer
set search_path = mod_mmn, public, extensions, auth, net, pg_temp
as $$
begin
  if not mod_mmn.fn_admin_tem_acesso('acessar') then
    return jsonb_build_object('ok', false, 'error', 'sem_permissao_mmn');
  end if;

  if coalesce(p_cod_usuario, 0) <= 0 then
    return jsonb_build_object('ok', false, 'error', 'usuario_invalido');
  end if;

  return jsonb_build_object(
    'ok', true,
    'rede', mod_mmn.fn_rede_usuario_json(p_cod_usuario)
  );
end;
$$;

grant usage on schema mod_mmn to anon, authenticated, service_role;
grant select on all tables in schema mod_mmn to authenticated;
grant all on all tables in schema mod_mmn to service_role;
grant execute on all functions in schema mod_mmn to authenticated, service_role;
grant execute on function public.mmn_usuario_painel_rpc() to authenticated;
grant execute on function public.adm_mmn_painel_rpc(date) to authenticated;
grant execute on function public.adm_mmn_rede_usuario_rpc(bigint) to authenticated;

commit;
