(function () {
  "use strict";

  var CONFIG={supabaseUrl:"https://jzqgudmvquokizvgehow.supabase.co",apiKey:"sb_publishable_eAPW_Kg8SLYpL43JVe104Q__qvEbyDU",sessionKey:"tt_admin_session_v1"};
  var state={session:null,contexto:null,conversas:[],selecionada:null,detalhe:null,setor:"",canal:"",serverUrl:"",syncing:false,mediaUrls:[],agendador:null,editCampaign:null};
  function el(id){return document.getElementById(id)}
  function readSession(){try{return JSON.parse(localStorage.getItem(CONFIG.sessionKey)||"null")}catch(e){return null}}
  function saveSession(value){state.session=value;localStorage.setItem(CONFIG.sessionKey,JSON.stringify(value))}
  function clearSession(){state.session=null;localStorage.removeItem(CONFIG.sessionKey)}
  async function parse(response){var text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw new Error((data&&(data.message||data.error))||"Falha de conexão");return data}
  async function session(){if(!state.session)state.session=readSession();if(!state.session||!state.session.access_token)return null;if(!state.session.expires_at||state.session.expires_at>Date.now()+60000)return state.session;var response=await fetch(CONFIG.supabaseUrl+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:CONFIG.apiKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:state.session.refresh_token})});var data=await parse(response);saveSession({access_token:data.access_token,refresh_token:data.refresh_token||state.session.refresh_token,expires_at:Date.now()+Number(data.expires_in||3600)*1000,user:data.user||state.session.user});return state.session}
  async function rpc(name,payload){var current=await session();if(!current){location.href="../";throw new Error("Sessão expirada")};return parse(await fetch(CONFIG.supabaseUrl+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:CONFIG.apiKey,Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify(payload||{})}))}
  function safe(value){return String(value==null?"":value)}
  function initials(name){return safe(name||"TT").split(/\s+/).slice(0,2).map(function(x){return x.charAt(0)}).join("").toUpperCase()}
  function renderAvatar(target,url,name){target.innerHTML="";target.style.overflow="hidden";var fallback=initials(name);target.textContent=fallback;if(!url)return;var image=document.createElement("img");image.alt="Foto de "+safe(name||"contato");image.loading="lazy";image.referrerPolicy="no-referrer";image.style.cssText="width:100%;height:100%;display:block;object-fit:cover";image.addEventListener("load",function(){target.textContent="";target.appendChild(image)});image.addEventListener("error",function(){target.textContent=fallback});image.src=url}
  function time(value){if(!value)return "—";return new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}
  function remaining(value){if(!value)return "—";var seconds=Math.max(0,Math.floor((new Date(value)-Date.now())/1000)),h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return (h<10?"0":"")+h+":"+(m<10?"0":"")+m}
  function channelName(value){return {whatsapp:"WhatsApp",instagram:"Instagram",messenger:"Messenger"}[value]||safe(value)}
  function statusName(value){return {nova:"Nova",triagem_ia:"IA em triagem",aguardando:"Aguardando",em_atendimento:"Em atendimento",pendente_cliente:"Aguardando cliente",resolvida:"Resolvida",fechada:"Fechada"}[value]||safe(value)}
  function renderList(){var query=el("conversationSearch").value.trim().toLowerCase();var rows=state.conversas.filter(function(c){return(!state.canal||c.canal.tipo===state.canal)&&(!query||safe(c.contato.nome+" "+c.contato.telefone+" "+c.ultima_mensagem).toLowerCase().indexOf(query)>=0)});el("countAll").textContent=state.conversas.length;document.querySelectorAll(".queue-button[data-sector]").forEach(function(btn){var key=btn.dataset.sector,count=key?state.conversas.filter(function(c){return c.setor.chave===key}).length:state.conversas.length;btn.querySelector("span").textContent=count});var wrap=el("conversationList");wrap.innerHTML="";if(!rows.length){wrap.innerHTML='<div class="empty-list">Nenhuma conversa nesta fila.</div>';return}rows.forEach(function(c){var b=document.createElement("button");b.type="button";b.className="conversation-row"+(state.selecionada&&state.selecionada.id===c.id?" is-active":"");b.innerHTML='<span class="channel-mark"></span><span class="conversation-copy"><strong></strong><span class="sector"></span><span class="preview"></span></span><span class="conversation-side"><time></time><span class="conversation-state"></span></span>';renderAvatar(b.querySelector(".channel-mark"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);b.querySelector("strong").textContent=c.contato.nome||c.contato.telefone;b.querySelector(".sector").textContent=c.setor.nome+" · "+channelName(c.canal.tipo);b.querySelector(".preview").textContent=c.ultima_mensagem||"Sem mensagem de texto";b.querySelector("time").textContent=time(c.ultima_mensagem_em);b.querySelector(".conversation-state").textContent=statusName(c.status);b.addEventListener("click",function(){selectConversation(c)});wrap.appendChild(b)})}
  async function loadConversations(silent){if(!silent)el("pageStatus").textContent="Atualizando";var selectedId=state.selecionada&&state.selecionada.id,selectedVersion=state.selecionada&&state.selecionada.versao;var data=await rpc("adm_atendimento_conversas_rpc",{p_setor:state.setor||null,p_status:null,p_limite:100});if(!data.ok)throw new Error(data.error);state.conversas=data.conversas||[];if(selectedId){var updated=state.conversas.find(function(c){return c.id===selectedId});if(updated){state.selecionada=updated;if(updated.versao!==selectedVersion)await refreshConversationDetail()}else state.selecionada=null}renderList();el("pageStatus").textContent=state.conversas.length+" conversa(s)"}
  async function selectConversation(c){state.selecionada=c;renderList();el("chatEmpty").hidden=true;el("chatContent").hidden=false;el("customerEmpty").hidden=true;el("customerContent").hidden=false;el("chatContact").textContent=c.contato.nome||c.contato.telefone;el("chatMeta").textContent=channelName(c.canal.tipo)+" · "+c.contato.telefone;el("customerName").textContent=c.contato.nome||"Contato";el("customerPhone").textContent=c.contato.telefone||"";el("customerAvatar").textContent=initials(c.contato.nome);el("detailChannel").textContent=channelName(c.canal.tipo);el("detailSector").textContent=c.setor.nome;el("detailAssignment").textContent=c.atendente?c.atendente.nome:statusName(c.status);el("detailWindow").textContent=c.janela_24h_ate?"Aberta · "+remaining(c.janela_24h_ate):"Sem janela";el("windowStatus").textContent="Janela "+remaining(c.janela_24h_ate);el("slaStatus").textContent="SLA "+remaining(c.primeira_resposta_ate);el("aiBanner").hidden=!c.ia_ativa;var currentAttendant=state.contexto&&state.contexto.atendente,isMine=!!(c.atendente&&currentAttendant&&Number(c.atendente.id)===Number(currentAttendant.id));el("takeConversationButton").disabled=!!c.atendente&&!isMine;el("takeConversationButton").textContent=c.atendente?(isMine?"Com "+c.atendente.nome+" · Voltar para IA":"Com "+c.atendente.nome):"Assumir conversa";await refreshConversationDetail()}
  async function refreshConversationDetail(){if(!state.selecionada)return;var selectedId=state.selecionada.id;var data=await rpc("adm_atendimento_conversa_rpc",{p_conversa:selectedId});if(!state.selecionada||state.selecionada.id!==selectedId)return;state.detalhe=data;renderDetail()}
  async function syncAutomatically(){if(state.syncing||document.hidden)return;state.syncing=true;try{await loadConversations(true)}catch(error){el("pageStatus").textContent="Reconectando automaticamente"}finally{state.syncing=false}}
  async function loadAudio(button,messageId){button.disabled=true;button.textContent="Carregando áudio...";try{var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/media?message_id="+encodeURIComponent(messageId),{headers:{Authorization:"Bearer "+current.access_token}});if(!response.ok)throw new Error("Áudio indisponível");var url=URL.createObjectURL(await response.blob());state.mediaUrls.push(url);var audio=document.createElement("audio");audio.controls=true;audio.autoplay=true;audio.preload="metadata";audio.src=url;audio.setAttribute("aria-label","Áudio recebido pelo WhatsApp");button.replaceWith(audio)}catch(error){button.disabled=false;button.textContent="Tentar ouvir novamente";button.title=error.message||String(error)}}
  function renderDetail(){var data=state.detalhe||{},stream=el("messageStream");state.mediaUrls.forEach(function(url){URL.revokeObjectURL(url)});state.mediaUrls=[];stream.innerHTML="";(data.mensagens||[]).forEach(function(m){var item=document.createElement("div");item.className="message"+(m.direcao==="saida"?" out":"");if(m.tipo==="audio"){var audioBox=document.createElement("div");audioBox.className="audio-message";var play=document.createElement("button");play.type="button";play.className="audio-play-button";play.textContent=m.midia_disponivel?"▶ Ouvir áudio":"Áudio indisponível";play.disabled=!m.midia_disponivel;if(m.midia_disponivel)play.addEventListener("click",function(){loadAudio(play,m.id)});audioBox.appendChild(play);var transcript=m.transcricao||m.texto||"";if(transcript){var transcription=document.createElement("div");transcription.className="audio-transcription";var label=document.createElement("strong");label.textContent="Transcrição";var paragraph=document.createElement("p");paragraph.textContent=transcript;transcription.append(label,paragraph);audioBox.appendChild(transcription)}item.appendChild(audioBox)}else{var text=document.createElement("div");text.textContent=m.texto||("["+m.tipo+"]");item.appendChild(text)}var meta=document.createElement("small");meta.textContent=(m.autor_tipo==="ia"?"IA · ":"")+time(m.criado_em)+" · "+m.status;item.appendChild(meta);stream.appendChild(item)});stream.scrollTop=stream.scrollHeight;var notes=el("notesList");notes.innerHTML="";(data.notas||[]).forEach(function(n){var d=document.createElement("div");d.textContent=n.texto;var small=document.createElement("small");small.textContent=new Date(n.criado_em).toLocaleString("pt-BR");d.appendChild(small);notes.appendChild(d)});if(!notes.children.length)notes.textContent="Nenhuma nota interna.";var audit=el("auditList");audit.innerHTML="";(data.auditoria||[]).slice(0,8).forEach(function(a){var d=document.createElement("div");d.textContent=safe(a.acao).replaceAll("_"," ");var small=document.createElement("small");small.textContent=new Date(a.criado_em).toLocaleString("pt-BR");d.appendChild(small);audit.appendChild(d)})}
  async function takeConversation(){var conversationId=state.selecionada.id,data=await rpc("adm_atendimento_assumir_rpc",{p_conversa:conversationId});if(!data.ok)throw new Error(data.error);var sendError=null;if(data.apresentacao_enviar&&data.apresentacao_texto){try{var current=await session(),response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,text:data.apresentacao_texto})}),sent=await parse(response);if(!sent.ok)throw new Error(sent.error||"Não foi possível enviar a apresentação")}catch(error){sendError=error}}await loadConversations();var updated=state.conversas.find(function(c){return c.id===conversationId});if(updated)await selectConversation(updated);if(sendError)throw new Error("A conversa foi assumida, mas a apresentação automática não foi enviada: "+(sendError.message||String(sendError)))}
  async function returnConversationToAi(){if(!state.selecionada||!confirm("Voltar esta conversa para o atendimento da IA?"))return;var conversationId=state.selecionada.id,data=await rpc("adm_atendimento_devolver_ia_rpc",{p_conversa:conversationId});if(!data.ok)throw new Error(data.error);await loadConversations();var updated=state.conversas.find(function(c){return c.id===conversationId});if(updated)await selectConversation(updated)}
  async function toggleConversationAssignment(){if(state.selecionada&&state.selecionada.atendente)return returnConversationToAi();return takeConversation()}
  async function sendMessage(event){event.preventDefault();if(!state.selecionada)return;var text=el("messageInput").value.trim();if(!text)return;var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:state.selecionada.id,text:text})});var data=await parse(response);if(!data.ok)throw new Error(data.error||"Não foi possível enviar");el("messageInput").value="";await selectConversation(state.selecionada)}
  async function saveNote(event){event.preventDefault();if(!state.selecionada)return;var text=el("noteInput").value.trim();if(!text)return;var data=await rpc("adm_atendimento_nota_salvar_rpc",{p_conversa:state.selecionada.id,p_texto:text});if(!data.ok)throw new Error(data.error);el("noteInput").value="";await selectConversation(state.selecionada)}
  function schedulerDefaultDate(){var date=new Date();date.setDate(date.getDate()+1);date.setHours(9,0,0,0);var offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerLocalDate(value){var date=new Date(value),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerStatusName(value){return {agendada:"Agendada",processando:"Enviando",concluida:"Concluída",cancelada:"Cancelada"}[value]||safe(value)}
  function schedulerFeedback(message,isError){var box=el("schedulerFeedback");box.textContent=message||"";box.classList.toggle("is-error",!!isError)}
  function renderSchedulerContacts(){var wrap=el("schedulerContacts");wrap.innerHTML="";var rows=state.conversas.filter(function(c){return c.canal&&c.canal.tipo==="whatsapp"});rows.forEach(function(c){var label=document.createElement("label");label.className="scheduler-contact";var input=document.createElement("input");input.type="checkbox";input.value=c.id;var text=document.createElement("span");text.textContent=(c.contato.nome||c.contato.telefone)+" · "+(c.contato.telefone||"");label.append(input,text);wrap.appendChild(label)});if(!rows.length){var empty=document.createElement("span");empty.textContent="Nenhuma conversa de WhatsApp carregada.";wrap.appendChild(empty)}}
  function renderSchedulerTemplates(){var select=el("schedulerTemplate"),templates=(state.agendador&&state.agendador.templates)||[];select.innerHTML="";templates.forEach(function(t){var option=document.createElement("option");option.value=t.id;option.textContent=t.nome+" · "+t.idioma+" · "+t.categoria;select.appendChild(option)});var templateRadio=document.querySelector('input[name="schedulerOutsideWindow"][value="template"]');templateRadio.disabled=!templates.length;el("schedulerTemplateHint").textContent=templates.length?"Somente templates com status aprovado pela Meta são exibidos.":"Nenhum template aprovado está disponível. Cadastre e sincronize um template antes de usar esta opção.";if(!templates.length&&templateRadio.checked){document.querySelector('input[name="schedulerOutsideWindow"][value="nao_enviar"]').checked=true}toggleSchedulerOutsideWindow()}
  function campaignCard(c){var card=document.createElement("article");card.className="scheduler-campaign";var header=document.createElement("header"),title=document.createElement("div"),h4=document.createElement("h4"),date=document.createElement("time"),status=document.createElement("span");h4.textContent=c.nome;date.textContent=new Date(c.agendada_para).toLocaleString("pt-BR");status.className="scheduler-status"+(c.status==="concluida"?" is-complete":c.status==="cancelada"?" is-cancelled":"");status.textContent=schedulerStatusName(c.status);title.append(h4,date);header.append(title,status);var instruction=document.createElement("p");instruction.textContent=c.instrucao_ia;var counts=document.createElement("div");counts.className="scheduler-counts";[["Destinatários",c.total_destinatarios],["Enviadas",c.total_enviados],["Ignoradas",c.total_ignorados],["Falhas",c.total_falhas]].forEach(function(item){var span=document.createElement("span");span.textContent=item[0]+": "+item[1];counts.appendChild(span)});var footer=document.createElement("footer");if(c.status==="agendada"){var edit=document.createElement("button");edit.type="button";edit.className="btn btn-ghost btn-small";edit.textContent="Editar";edit.addEventListener("click",function(){startEditScheduledCampaign(c)});footer.appendChild(edit)}if(c.status==="agendada"||c.status==="processando"){var cancel=document.createElement("button");cancel.type="button";cancel.className="btn btn-ghost btn-small";cancel.textContent="Cancelar";cancel.addEventListener("click",function(){cancelScheduledCampaign(c.id,c.nome).catch(function(error){schedulerFeedback(error.message||String(error),true)})});footer.appendChild(cancel)}card.append(header,instruction,counts,footer);return card}
  function renderSchedulerCampaigns(){var wrap=el("schedulerCampaigns"),campaigns=(state.agendador&&state.agendador.campanhas)||[];wrap.innerHTML="";if(!campaigns.length){var empty=document.createElement("p");empty.textContent="Nenhuma programação criada.";wrap.appendChild(empty);return}campaigns.forEach(function(c){wrap.appendChild(campaignCard(c))})}
  async function loadScheduler(){schedulerFeedback("Carregando programações...");var data=await rpc("adm_atendimento_agendador_contexto_rpc",{});if(!data.ok)throw new Error(data.error);state.agendador=data;renderSchedulerTemplates();renderSchedulerCampaigns();schedulerFeedback("")}
  async function openScheduler(){el("schedulerDate").value=el("schedulerDate").value||schedulerDefaultDate();renderSchedulerContacts();var dialog=el("schedulerDialog");if(!dialog.open)dialog.showModal();try{await loadScheduler()}catch(error){schedulerFeedback(error.message||String(error),true)}}
  function resetSchedulerForm(){state.editCampaign=null;el("schedulerForm").reset();el("schedulerDate").value=schedulerDefaultDate();document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=false});el("schedulerAudienceHint").textContent="";el("schedulerSubmit").textContent="Programar envio";el("schedulerCancel").textContent="Fechar";toggleSchedulerAudience();toggleSchedulerOutsideWindow();renderSchedulerContacts()}
  function closeScheduler(){resetSchedulerForm();if(el("schedulerDialog").open)el("schedulerDialog").close()}
  function cancelSchedulerForm(){if(state.editCampaign){resetSchedulerForm();schedulerFeedback("Edição cancelada.")}else closeScheduler()}
  function startEditScheduledCampaign(c){state.editCampaign=c;el("schedulerName").value=c.nome||"";el("schedulerDate").value=schedulerLocalDate(c.agendada_para);el("schedulerInstruction").value=c.instrucao_ia||"";document.querySelector('input[name="schedulerOutsideWindow"][value="'+c.fora_janela_acao+'"]').checked=true;if(c.template&&c.template.id)el("schedulerTemplate").value=c.template.id;document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=true});el("schedulerContacts").hidden=true;el("schedulerAudienceHint").textContent="Os "+c.total_destinatarios+" destinatários atuais serão preservados durante a edição.";el("schedulerSubmit").textContent="Salvar alterações";el("schedulerCancel").textContent="Cancelar edição";toggleSchedulerOutsideWindow();schedulerFeedback("Editando: "+c.nome);el("schedulerName").focus()}
  function toggleSchedulerAudience(){var selected=document.querySelector('input[name="schedulerAudience"]:checked');el("schedulerContacts").hidden=!selected||selected.value!=="selecionados"}
  function toggleSchedulerOutsideWindow(){var selected=document.querySelector('input[name="schedulerOutsideWindow"]:checked');el("schedulerTemplateField").hidden=!selected||selected.value!=="template"}
  async function createScheduledCampaign(event){event.preventDefault();schedulerFeedback("");var audience=document.querySelector('input[name="schedulerAudience"]:checked').value,outside=document.querySelector('input[name="schedulerOutsideWindow"]:checked').value,selected=Array.from(el("schedulerContacts").querySelectorAll('input[type="checkbox"]:checked')).map(function(input){return Number(input.value)});if(!state.editCampaign&&audience==="selecionados"&&!selected.length){schedulerFeedback("Selecione pelo menos um contato.",true);return}var localDate=el("schedulerDate").value;if(!localDate){schedulerFeedback("Escolha a data e o horário.",true);return}var submit=el("schedulerSubmit"),editing=state.editCampaign;submit.disabled=true;submit.textContent=editing?"Salvando...":"Programando...";try{var common={p_nome:el("schedulerName").value.trim(),p_instrucao_ia:el("schedulerInstruction").value.trim(),p_agendada_para:new Date(localDate).toISOString(),p_fora_janela_acao:outside,p_template:outside==="template"?Number(el("schedulerTemplate").value):null},data;if(editing){common.p_campanha=editing.id;data=await rpc("adm_atendimento_agendamento_editar_rpc",common)}else{common.p_publico_tipo=audience;common.p_conversas=selected;data=await rpc("adm_atendimento_agendamento_criar_rpc",common)}if(!data.ok)throw new Error(data.error);resetSchedulerForm();await loadScheduler();schedulerFeedback(editing?"Programação atualizada com sucesso.":"Programação criada para "+data.total_destinatarios+" contato(s).") }catch(error){schedulerFeedback(error.message||String(error),true)}finally{submit.disabled=false;submit.textContent=state.editCampaign?"Salvar alterações":"Programar envio"}}
  async function cancelScheduledCampaign(id,name){if(!confirm('Cancelar a programação "'+name+'"? Mensagens já enviadas não serão afetadas.'))return;var data=await rpc("adm_atendimento_agendamento_cancelar_rpc",{p_campanha:id});if(!data.ok)throw new Error(data.error);schedulerFeedback("Programação cancelada.");await loadScheduler()}
  async function init(){try{state.session=readSession();if(!state.session){location.href="../";return}var admin=await rpc("adm_contexto_rpc",{});if(!admin.ok||!Array.isArray(admin.areas)||(admin.areas.indexOf("atendimento")<0&&admin.areas.indexOf("admin")<0))throw new Error("Sem permissão para Atendimento");state.contexto=await rpc("adm_atendimento_contexto_rpc",{});if(!state.contexto.ok)throw new Error(state.contexto.error);el("adminIdentity").textContent=(state.contexto.atendente&&state.contexto.atendente.nome)||(state.session.user&&state.session.user.email)||"Turbo Tiger";state.serverUrl=await rpc("app_config_buscar_rpc",{p_categoria:"turbotiger_urls",p_tipo:"servidor_whatsapp"});if(typeof state.serverUrl!=="string"||!state.serverUrl)throw new Error("Servidor de atendimento não configurado");await loadConversations();setInterval(syncAutomatically,3000);document.addEventListener("visibilitychange",function(){if(!document.hidden)syncAutomatically()})}catch(error){el("pageStatus").textContent=error.message||String(error);el("pageStatus").classList.add("is-error")}}
  document.querySelectorAll(".queue-button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".queue-button").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.setor=b.dataset.sector;loadConversations().catch(alert)})});document.querySelectorAll(".channel-tab").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".channel-tab").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.canal=b.dataset.channel;renderList()})});document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.addEventListener("change",toggleSchedulerAudience)});document.querySelectorAll('input[name="schedulerOutsideWindow"]').forEach(function(input){input.addEventListener("change",toggleSchedulerOutsideWindow)});el("conversationSearch").addEventListener("input",renderList);el("reloadButton").addEventListener("click",function(){loadConversations().catch(alert)});el("takeConversationButton").addEventListener("click",function(){toggleConversationAssignment().catch(alert)});el("messageForm").addEventListener("submit",function(e){sendMessage(e).catch(alert)});el("noteForm").addEventListener("submit",function(e){saveNote(e).catch(alert)});el("schedulerButton").addEventListener("click",function(){openScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerClose").addEventListener("click",closeScheduler);el("schedulerCancel").addEventListener("click",cancelSchedulerForm);el("schedulerReload").addEventListener("click",function(){loadScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerForm").addEventListener("submit",createScheduledCampaign);el("schedulerDialog").addEventListener("click",function(event){if(event.target===el("schedulerDialog"))closeScheduler()});el("logoutButton").addEventListener("click",function(){clearSession();location.href="../"});el("templatesButton").addEventListener("click",function(){alert("Gestão de templates será aberta na próxima etapa de configuração da Meta.")});el("chooseTemplateButton").addEventListener("click",function(){alert("Selecione um template aprovado quando a janela de 24 horas estiver fechada.")});el("settingsButton").addEventListener("click",function(){alert("Configurações de canais, setores e atendentes são restritas à supervisão.")});init();
})();
