(function () {
  "use strict";
  var LEGENDAS_ATENDIMENTO = {
  "legenda_fechamento_atendimento_fila_vazia": "Nenhuma conversa nesta fila.",
  "legenda_fechamento_atendimento_atualizando": "Atualizando",

"legenda_atendimento_agendador_fechar":"Fechar",
"legenda_atendimento_agendador_salvando":"Salvando...",
"legenda_atendimento_agendador_programando":"Programando...",
"legenda_atendimento_agendador_programacao_criada_quantidade":"Programação criada para {quantidade} contato(s).",
"legenda_atendimento_frase_enviadas":"Enviadas",
"legenda_atendimento_frase_ignoradas":"Ignoradas",
"legenda_atendimento_frase_falhas":"Falhas",
"legenda_atendimento_frase_janela_tempo":"Janela {tempo}",
"legenda_atendimento_frase_com_atendente":"Com {atendente}",
"legenda_atendimento_frase_quantidade_conversas":"{quantidade} conversa(s)",
"legenda_atendimento_frase_enviando":"Enviando",
"legenda_atendimento_frase_destinatarios_preservados_quantidade":"Os {quantidade} destinatários atuais serão preservados durante a edição.",
"legenda_atendimento_frase_editando_nome":"Editando: {nome}",
"legenda_atendimento_foto_de": "Foto de ",
"legenda_atendimento_status_atualizado": "Status atualizado: ",
"legenda_atendimento_assuma_uma_conversa_para_responder": "Assuma uma conversa para responder",
"legenda_atendimento_conversa_em_atendimento_por": "Conversa em atendimento por ",
"legenda_atendimento_outro_atendente": "outro atendente",
"legenda_atendimento_assuma_a_conversa_para_responder": "Assuma a conversa para responder.",
"legenda_atendimento_a_conversa_nao_esta_em_atendimento": "A conversa não está em atendimento.",
"legenda_atendimento_janela_de_atendimento_encerrada_use_um_template_aprovado": "Janela de atendimento encerrada. Use um template aprovado.",
"legenda_atendimento_dentro_da_janela_de_atendimento": "Dentro da janela de atendimento",
"legenda_atendimento_aberta": "Aberta · ",
"legenda_atendimento_fechada": "Fechada",
"legenda_atendimento_janela_fechada": "Janela fechada",
"legenda_atendimento_sla_humano": "SLA humano ",
"legenda_atendimento_sla_humano_vencido": "SLA humano vencido",
"legenda_atendimento_sla_humano_atendido": "SLA humano atendido",
"legenda_atendimento_sla_humano_sem_prazo": "SLA humano —",
"legenda_atendimento_contato": "Contato",
"legenda_atendimento_voltar_para_ia": " · Voltar para IA",
"legenda_atendimento_assumir_conversa": "Assumir conversa",
"legenda_atendimento_aguardando_atendimento_humano_a_ia_permanece_apenas_na_recepcao_durante_a_espera": "Aguardando atendimento humano. A IA permanece apenas na recepção durante a espera.",
"legenda_atendimento_a_ia_esta_fazendo_a_triagem_inicial_assuma_a_conversa_para_interromper": "A IA está fazendo a triagem inicial. Assuma a conversa para interromper a automação.",
"legenda_atendimento_sem_mensagem_de_texto": "Sem mensagem de texto",
"legenda_atendimento_audio_recebido_pelo_whatsapp": "Áudio recebido pelo WhatsApp",
"legenda_atendimento_ia": "IA · ",
"legenda_atendimento_atendente": "Atendente · ",
"legenda_atendimento_agendada": "Agendada",
"legenda_atendimento_concluida": "Concluída",
"legenda_atendimento_cancelada": "Cancelada",
"legenda_atendimento_somente_templates_com_status_aprovado_pela_meta_sao_exibidos": "Somente templates com status aprovado pela Meta são exibidos.",
"legenda_atendimento_nenhum_template_aprovado_esta_disponivel_cadastre_e_sincronize_um_template_antes_de": "Nenhum template aprovado está disponível. Cadastre e sincronize um template antes de usar esta opção.",
"legenda_atendimento_destinatarios": "Destinatários",
"legenda_atendimento_editar": "Editar",
"legenda_atendimento_cancelar": "Cancelar",
"legenda_atendimento_carregando_programacoes": "Carregando programações...",
"legenda_atendimento_programar_envio": "Programar envio",
"legenda_atendimento_edicao_cancelada": "Edição cancelada.",
"legenda_atendimento_destinatarios_atuais_serao_preservados_durante_a_edicao": " destinatários atuais serão preservados durante a edição.",
"legenda_atendimento_salvar_alteracoes": "Salvar alterações",
"legenda_atendimento_cancelar_edicao": "Cancelar edição",
"legenda_atendimento_selecione_pelo_menos_um_contato": "Selecione pelo menos um contato.",
"legenda_atendimento_escolha_a_data_e_o_horario": "Escolha a data e o horário.",
"legenda_atendimento_programacao_atualizada_com_sucesso": "Programação atualizada com sucesso.",
"legenda_atendimento_programacao_criada_para": "Programação criada para ",
"legenda_atendimento_cancelar_a_programacao": "Cancelar a programação \"",
"legenda_atendimento_mensagens_ja_enviadas_nao_serao_afetadas": "\"? Mensagens já enviadas não serão afetadas.",
"legenda_atendimento_programacao_cancelada": "Programação cancelada.",
"legenda_atendimento_gestao_de_templates_sera_aberta_na_proxima_etapa_de_configuracao_da_meta": "Gestão de templates será aberta na próxima etapa de configuração da Meta.",
"legenda_atendimento_selecione_um_template_aprovado_quando_a_janela_de_24_horas_estiver_fechada": "Selecione um template aprovado quando a janela de 24 horas estiver fechada.",
"legenda_atendimento_configuracoes_de_canais_setores_e_atendentes_sao_restritas_a_supervisao": "Configurações de canais, setores e atendentes são restritas à supervisão.",
  "legenda_atendimento_conversa_nova": "Nova",
  "legenda_atendimento_conversa_triagem_ia": "IA em triagem",
  "legenda_atendimento_conversa_aguardando_humano": "Aguardando humano",
  "legenda_atendimento_conversa_em_atendimento": "Em atendimento",
  "legenda_atendimento_conversa_pendente_cliente": "Aguardando cliente",
  "legenda_atendimento_conversa_resolvida": "Resolvida",
  "legenda_atendimento_conversa_fechada": "Fechada",
  "legenda_atendimento_mensagem_recebida": "recebida",
  "legenda_atendimento_mensagem_aceita": "aceita",
  "legenda_atendimento_mensagem_enviada": "enviada",
  "legenda_atendimento_mensagem_entregue": "entregue",
  "legenda_atendimento_mensagem_lida": "lida",
  "legenda_atendimento_mensagem_falhou": "falhou",
  "legenda_atendimento_mensagem_enviando": "enviando",
  "legenda_atendimento_mensagem_processando": "processando",
  "legenda_atendimento_reconectando": "Reconectando automaticamente",
  "legenda_atendimento_puxe_atualizar": "Puxe para atualizar",
  "legenda_atendimento_solte_atualizar": "Solte para atualizar",
  "legenda_atendimento_atualizando": "Atualizando...",
  "legenda_atendimento_atualizado": "Atualizado",
  "legenda_atendimento_atualizacao_falhou": "Não foi possível atualizar",
  "legenda_atendimento_audio_carregando": "Carregando áudio...",
  "legenda_atendimento_audio_tentar_novamente": "Tentar ouvir novamente",
  "legenda_atendimento_audio_ouvir": "▶ Ouvir áudio",
  "legenda_atendimento_audio_indisponivel": "Áudio indisponível",
  "legenda_atendimento_transcricao": "Transcrição",
  "legenda_atendimento_transcricao_indisponivel": "Transcrição indisponível",
  "legenda_atendimento_transcricao_falhou": "Não foi possível transcrever este áudio.",
  "legenda_atendimento_transcricao_processando": "Transcrevendo áudio...",
  "legenda_atendimento_notas_vazias": "Nenhuma nota interna.",
  "legenda_atendimento_conversas_whatsapp_vazias": "Nenhuma conversa de WhatsApp carregada.",
  "legenda_atendimento_programacoes_vazias": "Nenhuma programação criada.",
  "legenda_atendimento_erro_conexao": "Falha de conexão",
  "legenda_atendimento_erro_sessao_expirada": "Sessão expirada",
  "legenda_atendimento_erro_atualizar_status": "Não foi possível atualizar seu status",
  "legenda_atendimento_erro_atualizar_conversa": "Não foi possível atualizar a conversa",
  "legenda_atendimento_erro_enviar_apresentacao": "Não foi possível enviar a apresentação",
  "legenda_atendimento_erro_apresentacao_apos_assumir": "A conversa foi assumida, mas a apresentação automática não foi enviada: {erro}",
  "legenda_atendimento_erro_enviar_despedida": "Não foi possível enviar a despedida automática",
  "legenda_atendimento_erro_enviar": "Não foi possível enviar",
  "legenda_atendimento_erro_sem_permissao": "Sem permissão para Atendimento",
  "legenda_atendimento_erro_servidor_configuracao": "Servidor de atendimento não configurado"
};
  var LEGENDAS_ESTADOS_CONVERSA = {"nova":"legenda_atendimento_conversa_nova","triagem_ia":"legenda_atendimento_conversa_triagem_ia","aguardando":"legenda_atendimento_conversa_aguardando_humano","em_atendimento":"legenda_atendimento_conversa_em_atendimento","pendente_cliente":"legenda_atendimento_conversa_pendente_cliente","resolvida":"legenda_atendimento_conversa_resolvida","fechada":"legenda_atendimento_conversa_fechada"};
  var LEGENDAS_ESTADOS_MENSAGEM = {"received":"legenda_atendimento_mensagem_recebida","recebida":"legenda_atendimento_mensagem_recebida","accepted":"legenda_atendimento_mensagem_aceita","sent":"legenda_atendimento_mensagem_enviada","delivered":"legenda_atendimento_mensagem_entregue","read":"legenda_atendimento_mensagem_lida","failed":"legenda_atendimento_mensagem_falhou","pending":"legenda_atendimento_mensagem_enviando","processing":"legenda_atendimento_mensagem_processando"};
  function chaveEstadoLegenda(mapa,valor){return Object.prototype.hasOwnProperty.call(mapa,valor)?mapa[valor]:null;}
  var vinculosEstadoLegenda = new WeakMap();
  if(window.TurboTigerLegendas) window.TurboTigerLegendas.registrar(LEGENDAS_ATENDIMENTO);
  function legendaAtendimento(chave,parametros){if(window.TurboTigerLegendas)return window.TurboTigerLegendas.texto(chave,parametros);return LEGENDAS_ATENDIMENTO[chave].replace(/\{([a-z][a-z0-9_]*)\}/g,function(original,nome){return parametros&&Object.prototype.hasOwnProperty.call(parametros,nome)?String(parametros[nome]):original;});}
  function desvincularEstadoLegenda(target){if(!target)return;target.removeAttribute("data-atendimento-legenda");vinculosEstadoLegenda.delete(target);}
  function vincularEstadoLegenda(target,chave,fallback){
    if(!target)return;
    if(!chave){desvincularEstadoLegenda(target);target.textContent=fallback;return;}
    var texto=legendaAtendimento(chave);target.textContent=texto;target.setAttribute("data-atendimento-legenda",chave);vinculosEstadoLegenda.set(target,{chave:chave,texto:texto});
  }
  window.addEventListener("turbotiger:idioma",function(){
    document.querySelectorAll("[data-atendimento-legenda]").forEach(function(target){var vinculo=vinculosEstadoLegenda.get(target);if(!vinculo||target.textContent!==vinculo.texto)return;vinculo.texto=legendaAtendimento(vinculo.chave);target.textContent=vinculo.texto;});
  });


  var CONFIG={supabaseUrl:"https://jzqgudmvquokizvgehow.supabase.co",apiKey:"sb_publishable_eAPW_Kg8SLYpL43JVe104Q__qvEbyDU",sessionKey:"tt_admin_session_v1"};
  var state={session:null,contexto:null,conversas:[],selecionada:null,detalhe:null,setor:"",canal:"",serverUrl:"",syncing:false,mediaUrls:new Map(),pulseToken:null,pulseAvailable:true,pulseRetryAt:0,agendador:null,editCampaign:null};
  function el(id){return document.getElementById(id)}
  function readSession(){try{return JSON.parse(localStorage.getItem(CONFIG.sessionKey)||"null")}catch(e){return null}}
  function saveSession(value){state.session=value;localStorage.setItem(CONFIG.sessionKey,JSON.stringify(value))}
  function clearSession(){state.session=null;localStorage.removeItem(CONFIG.sessionKey)}
  async function parse(response){var text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw new Error((data&&(data.message||data.error))||legendaAtendimento("legenda_atendimento_erro_conexao"));return data}
  async function session(){if(!state.session)state.session=readSession();if(!state.session||!state.session.access_token)return null;if(!state.session.expires_at||state.session.expires_at>Date.now()+60000)return state.session;var response=await fetch(CONFIG.supabaseUrl+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:CONFIG.apiKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:state.session.refresh_token})});var data=await parse(response);saveSession({access_token:data.access_token,refresh_token:data.refresh_token||state.session.refresh_token,expires_at:Date.now()+Number(data.expires_in||3600)*1000,user:data.user||state.session.user});return state.session}
  async function rpc(name,payload){var current=await session();if(!current){location.href="../";throw new Error(legendaAtendimento("legenda_atendimento_erro_sessao_expirada"))};return parse(await fetch(CONFIG.supabaseUrl+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:CONFIG.apiKey,Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify(payload||{})}))}

  var textosComplementaresAtendimento=new Map();
  function aplicarTextoAtendimento(elemento,obter){var texto=obter();elemento.textContent=texto;textosComplementaresAtendimento.set(elemento,{obter:obter,ultimo:elemento.textContent});return texto;}
  window.addEventListener("turbotiger:idioma",function(){textosComplementaresAtendimento.forEach(function(v,e){if(!e.isConnected||e.textContent!==v.ultimo){textosComplementaresAtendimento.delete(e);return;}e.textContent=v.obter();v.ultimo=e.textContent;});});
  function safe(value){return String(value==null?"":value)}
  function initials(name){var text=safe(name||"TT").normalize("NFC").trim(),first=text.match(/^[\p{L}\p{N}]+/u),parts=text.match(/[\p{L}\p{N}]+/gu)||[];if(!parts.length)return"TT";var firstLetters=Array.from(parts[0]);if((first&&/^\s+[^\p{L}\p{N}]/u.test(text.slice(first[0].length)))||parts.length===1)return firstLetters.slice(0,2).join("").toLocaleUpperCase("pt-BR");return(firstLetters[0]+Array.from(parts[1])[0]).toLocaleUpperCase("pt-BR")}
  function titleName(name){return safe(name).normalize("NFC").trim().toLocaleLowerCase("pt-BR").replace(/(^|\s)([\p{L}])/gu,function(_,space,letter){return space+letter.toLocaleUpperCase("pt-BR")})}
  function renderAvatar(target,url,name){target.innerHTML="";target.style.overflow="hidden";var fallback=initials(name);target.textContent=fallback;if(!url)return;var image=document.createElement("img");image.alt=legendaAtendimento("legenda_atendimento_foto_de")+safe(name||"contato");image.loading="lazy";image.referrerPolicy="no-referrer";image.style.cssText="width:100%;height:100%;display:block;object-fit:cover";image.addEventListener("load",function(){target.textContent="";target.appendChild(image)});image.addEventListener("error",function(){target.textContent=fallback});image.src=url}
  function time(value){if(!value)return "—";return new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}
  function remaining(value){if(!value)return "—";var seconds=Math.max(0,Math.floor((new Date(value)-Date.now())/1000)),h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return (h<10?"0":"")+h+":"+(m<10?"0":"")+m}
  function channelName(value){return {whatsapp:"WhatsApp",instagram:"Instagram",messenger:"Messenger"}[value]||safe(value)}
  function statusName(value){var chave=chaveEstadoLegenda(LEGENDAS_ESTADOS_CONVERSA,value);return chave?legendaAtendimento(chave):safe(value)}
  function messageStatusName(value){var chave=chaveEstadoLegenda(LEGENDAS_ESTADOS_MENSAGEM,safe(value).toLowerCase());return chave?legendaAtendimento(chave):safe(value).replaceAll("_"," ")}
  function isFuture(value){return !!value&&!Number.isNaN(new Date(value).getTime())&&new Date(value).getTime()>Date.now()}
  function currentAttendant(){return state.contexto&&state.contexto.atendente}
  function isMine(c){var attendant=currentAttendant();return !!(c&&c.atendente&&attendant&&Number(c.atendente.id)===Number(attendant.id))}
  function releaseMediaUrl(messageId){var key=safe(messageId),url=state.mediaUrls.get(key);if(url){URL.revokeObjectURL(url);state.mediaUrls.delete(key)}}
  function releaseAllMediaUrls(){state.mediaUrls.forEach(function(url){URL.revokeObjectURL(url)});state.mediaUrls.clear()}
  function setAttendantStatus(status){var value=["online","ocupado","pausa","offline"].indexOf(status)>=0?status:"offline",select=el("agentStatus"),label=select&&select.closest(".agent-status");if(select)select.value=value;if(label)label.dataset.status=value;if(state.contexto&&state.contexto.atendente)state.contexto.atendente.status=value}
  async function saveAttendantStatus(){var select=el("agentStatus"),previous=(state.contexto&&state.contexto.atendente&&state.contexto.atendente.status)||"offline",wanted=select.value;select.disabled=true;try{var data=await rpc("adm_atendimento_atendente_status_rpc",{p_status:wanted});if(!data||!data.ok)throw new Error((data&&data.error)||legendaAtendimento("legenda_atendimento_erro_atualizar_status"));setAttendantStatus(data.status||wanted);el("pageStatus").classList.remove("is-error");aplicarTextoAtendimento(el("pageStatus"),function(){return legendaAtendimento("legenda_atendimento_status_atualizado")+titleName(data.status||wanted)})}catch(error){setAttendantStatus(previous);el("pageStatus").textContent=error.message||String(error);el("pageStatus").classList.add("is-error")}finally{select.disabled=!currentAttendant()}}
  function createLink(url,label){var link=document.createElement("a");link.className="message-link";link.href=url;link.target="_blank";link.rel="noopener noreferrer";link.textContent=label||url;return link}
  function appendPlainUrl(target,raw){var url=raw,trailing="";while(/[.,!?;:\]\}]$/.test(url)){trailing=url.slice(-1)+trailing;url=url.slice(0,-1)}target.appendChild(createLink(url,url));if(trailing)target.appendChild(document.createTextNode(trailing))}
  function renderFormattedText(target,value){desvincularEstadoLegenda(target);textosComplementaresAtendimento.delete(target);target.innerHTML="";var source=safe(value),pattern=/\[([^\]\n]{1,240})\]\((https?:\/\/[^\s)]+)\)|(https?:\/\/[^\s<]+)|\*([^*\n]+)\*/g,last=0,match;while((match=pattern.exec(source))!==null){if(match.index>last)target.appendChild(document.createTextNode(source.slice(last,match.index)));if(match[2])target.appendChild(createLink(match[2],match[1]));else if(match[3])appendPlainUrl(target,match[3]);else{var strong=document.createElement("strong");strong.textContent=match[4];target.appendChild(strong)}last=pattern.lastIndex}if(last<source.length)target.appendChild(document.createTextNode(source.slice(last)))}
  function clearSelection(){releaseAllMediaUrls();state.selecionada=null;state.detalhe=null;el("chatEmpty").hidden=false;el("chatContent").hidden=true;el("customerEmpty").hidden=false;el("customerContent").hidden=true;el("messageStream").innerHTML="";el("messageInput").value="";updateComposerState()}
  function updateComposerState(){var c=state.selecionada,attendant=currentAttendant(),open=!!(c&&isFuture(c.janela_24h_ate)),mine=isMine(c),other=!!(c&&c.atendente&&!mine),inService=!!(c&&c.status==="em_atendimento"),enabled=!!(c&&attendant&&open&&mine&&inService),input=el("messageInput"),send=el("sendButton"),template=el("chooseTemplateButton"),hint=el("composerHint");input.disabled=!enabled;send.disabled=!enabled;template.disabled=!(c&&attendant&&!open&&mine&&inService);if(!c)aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_assuma_uma_conversa_para_responder")});else if(other)aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_conversa_em_atendimento_por")+titleName(c.atendente.nome||legendaAtendimento("legenda_atendimento_outro_atendente"))+"."});else if(!mine)aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_assuma_a_conversa_para_responder")});else if(!inService)aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_a_conversa_nao_esta_em_atendimento")});else if(!open)aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_janela_de_atendimento_encerrada_use_um_template_aprovado")});else aplicarTextoAtendimento(hint,function(){return legendaAtendimento("legenda_atendimento_dentro_da_janela_de_atendimento")})}
  function updateSelectedTimeState(){var c=state.selecionada;if(!c)return;aplicarTextoAtendimento(el("detailWindow"),function(){return isFuture(c.janela_24h_ate)?legendaAtendimento("legenda_atendimento_aberta")+remaining(c.janela_24h_ate):legendaAtendimento("legenda_atendimento_fechada")});aplicarTextoAtendimento(el("windowStatus"),function(){return isFuture(c.janela_24h_ate)?legendaAtendimento("legenda_atendimento_frase_janela_tempo",{tempo:remaining(c.janela_24h_ate)}):legendaAtendimento("legenda_atendimento_janela_fechada")});var sla=el("slaStatus");if(c.status==="aguardando"&&c.primeira_resposta_ate)aplicarTextoAtendimento(sla,function(){return isFuture(c.primeira_resposta_ate)?legendaAtendimento("legenda_atendimento_sla_humano")+remaining(c.primeira_resposta_ate):legendaAtendimento("legenda_atendimento_sla_humano_vencido")});else if(c.status==="em_atendimento")aplicarTextoAtendimento(sla,function(){return legendaAtendimento("legenda_atendimento_sla_humano_atendido")});else aplicarTextoAtendimento(sla,function(){return legendaAtendimento("legenda_atendimento_sla_humano_sem_prazo")});updateComposerState()}
  function renderConversationHeader(c){if(!c)return;el("chatContact").textContent=c.contato.nome||c.contato.telefone;el("chatMeta").textContent=channelName(c.canal.tipo)+" · "+c.contato.telefone;aplicarTextoAtendimento(el("customerName"),function(){return c.contato.nome||legendaAtendimento("legenda_atendimento_contato")});el("customerPhone").textContent=c.contato.telefone||"";renderAvatar(el("chatAvatar"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);renderAvatar(el("customerAvatar"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);el("detailChannel").textContent=channelName(c.canal.tipo);el("detailSector").textContent=c.setor.nome;var attendantName=c.atendente?titleName(c.atendente.nome):"",assignmentButton=el("takeConversationButton"),mine=isMine(c);vincularEstadoLegenda(el("detailAssignment"),c.atendente?null:chaveEstadoLegenda(LEGENDAS_ESTADOS_CONVERSA,c.status),c.atendente?attendantName:statusName(c.status));assignmentButton.disabled=!!c.atendente&&!mine;aplicarTextoAtendimento(assignmentButton,function(){return c.atendente?(mine?legendaAtendimento("legenda_atendimento_frase_com_atendente",{atendente:attendantName})+legendaAtendimento("legenda_atendimento_voltar_para_ia"):legendaAtendimento("legenda_atendimento_frase_com_atendente",{atendente:attendantName})):legendaAtendimento("legenda_atendimento_assumir_conversa")});assignmentButton.style.backgroundColor=c.atendente?"#168a4a":"";assignmentButton.style.borderColor=c.atendente?"#168a4a":"";assignmentButton.style.color=c.atendente?"#fff":"";var banner=el("aiBanner");banner.hidden=!c.ia_ativa||c.status==="em_atendimento";aplicarTextoAtendimento(banner,function(){return c.status==="aguardando"?legendaAtendimento("legenda_atendimento_aguardando_atendimento_humano_a_ia_permanece_apenas_na_recepcao_durante_a_espera"):legendaAtendimento("legenda_atendimento_a_ia_esta_fazendo_a_triagem_inicial_assuma_a_conversa_para_interromper")});updateSelectedTimeState()}
  function renderList(){
    var query=el("conversationSearch").value.trim().toLocaleLowerCase("pt-BR");
    var rows=state.conversas.filter(function(c){return(!state.canal||c.canal.tipo===state.canal)&&(!query||safe(c.contato.nome+" "+c.contato.telefone+" "+c.ultima_mensagem).toLocaleLowerCase("pt-BR").indexOf(query)>=0)});
    if(state.selecionada&&!rows.some(function(c){return c.id===state.selecionada.id}))clearSelection();
    el("countAll").textContent=state.conversas.length;
    document.querySelectorAll(".queue-button[data-sector]").forEach(function(btn){var key=btn.dataset.sector,count=key?state.conversas.filter(function(c){return c.setor.chave===key}).length:state.conversas.length;btn.querySelector("span").textContent=count});
    var wrap=el("conversationList");wrap.innerHTML="";
    if(!rows.length){wrap.innerHTML="<div class=\"empty-list\"></div>";aplicarTextoAtendimento(wrap.firstElementChild,function(){return legendaAtendimento("legenda_fechamento_atendimento_fila_vazia")});return}
    rows.forEach(function(c){var b=document.createElement("button");b.type="button";b.className="conversation-row"+(state.selecionada&&state.selecionada.id===c.id?" is-active":"");b.innerHTML='<span class="channel-mark"></span><span class="conversation-copy"><strong></strong><span class="sector"></span><span class="preview"></span></span><span class="conversation-side"><time></time><span class="conversation-state"></span></span>';renderAvatar(b.querySelector(".channel-mark"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);b.querySelector("strong").textContent=c.contato.nome||c.contato.telefone;b.querySelector(".sector").textContent=c.setor.nome+" · "+channelName(c.canal.tipo);aplicarTextoAtendimento(b.querySelector(".preview"),function(){return c.ultima_mensagem||legendaAtendimento("legenda_atendimento_sem_mensagem_de_texto")});b.querySelector("time").textContent=time(c.ultima_mensagem_em);var status=b.querySelector(".conversation-state");vincularEstadoLegenda(status,chaveEstadoLegenda(LEGENDAS_ESTADOS_CONVERSA,c.status),statusName(c.status));if(c.status==="aguardando"){status.style.background="#fee2e2";status.style.color="#b42318"}else if(c.status==="em_atendimento"){status.style.background="#dcfce7";status.style.color="#168a4a"}b.addEventListener("click",function(){selectConversation(c)});wrap.appendChild(b)})
  }
  async function loadConversations(silent,forceDetail){
    if(!silent)aplicarTextoAtendimento(el("pageStatus"),function(){return legendaAtendimento("legenda_fechamento_atendimento_atualizando")});
    var selectedId=state.selecionada&&state.selecionada.id,selectedVersion=state.selecionada&&state.selecionada.versao;
    var data=await rpc("adm_atendimento_conversas_rpc",{p_setor:state.setor||null,p_status:null,p_limite:100});
    if(!data.ok)throw new Error(data.error);
    state.conversas=data.conversas||[];
    if(selectedId){
      var updated=state.conversas.find(function(c){return c.id===selectedId});
      if(updated){state.selecionada=updated;renderConversationHeader(updated);if(forceDetail||!silent||updated.versao!==selectedVersion)await refreshConversationDetail()}
      else clearSelection()
    }
    renderList();
    el("pageStatus").classList.remove("is-error");
    aplicarTextoAtendimento(el("pageStatus"),function(){return legendaAtendimento("legenda_atendimento_frase_quantidade_conversas",{quantidade:state.conversas.length})})
  }
  async function selectConversation(c){
    var changed=!state.selecionada||state.selecionada.id!==c.id;
    if(changed){releaseAllMediaUrls();state.detalhe=null;el("messageStream").innerHTML="";el("messageInput").value=""}
    state.selecionada=c;
    el("chatEmpty").hidden=true;el("chatContent").hidden=false;el("customerEmpty").hidden=true;el("customerContent").hidden=false;
    renderConversationHeader(c);renderList();await refreshConversationDetail()
  }
  async function refreshConversationDetail(){if(!state.selecionada)return;var selectedId=state.selecionada.id;var data=await rpc("adm_atendimento_conversa_rpc",{p_conversa:selectedId});if(!data||!data.ok)throw new Error((data&&data.error)||legendaAtendimento("legenda_atendimento_erro_atualizar_conversa"));if(!state.selecionada||state.selecionada.id!==selectedId)return;state.detalhe=data;renderDetail()}
  async function readPulse(){var data=await rpc("adm_atendimento_pulso_rpc",{});if(!data||!data.ok||data.token==null)throw new Error((data&&data.error)||"pulso_indisponivel");return safe(data.token)}
  async function initializePulse(){try{state.pulseToken=await readPulse();state.pulseAvailable=true;state.pulseRetryAt=0}catch(error){state.pulseAvailable=false;state.pulseRetryAt=Date.now()+60000}}
  async function syncAutomatically(){
    if(state.syncing||document.hidden)return;
    state.syncing=true;
    try{
      if(state.pulseAvailable){
        try{var token=await readPulse();if(state.pulseToken!==token){state.pulseToken=token;await loadConversations(true,true)}}catch(error){state.pulseAvailable=false;state.pulseRetryAt=Date.now()+60000;await loadConversations(true,true)}
      }else if(Date.now()>=state.pulseRetryAt){
        try{state.pulseToken=await readPulse();state.pulseAvailable=true;state.pulseRetryAt=0;await loadConversations(true,true)}catch(error){state.pulseRetryAt=Date.now()+60000;await loadConversations(true,true)}
      }else await loadConversations(true,true)
    }catch(error){vincularEstadoLegenda(el("pageStatus"),"legenda_atendimento_reconectando","");el("pageStatus").classList.add("is-error")}
    finally{state.syncing=false}
  }
  async function refreshVisibleData(){if(state.syncing)return;state.syncing=true;try{await loadConversations(true,true);var dialog=el("schedulerDialog");if(dialog&&dialog.open)await loadScheduler()}finally{state.syncing=false}}
  function initPullToRefresh(){var indicator=el("pullRefresh"),startY=0,distance=0,pulling=false,threshold=72;if(!indicator||!window.matchMedia("(max-width: 850px)").matches)return;function reset(){pulling=false;distance=0;indicator.classList.remove("is-pulling","is-ready","is-refreshing");indicator.style.transform="";indicator.hidden=true;vincularEstadoLegenda(indicator,"legenda_atendimento_puxe_atualizar","")}document.addEventListener("touchstart",function(event){if(event.touches.length!==1||window.scrollY>0||state.syncing)return;startY=event.touches[0].clientY;distance=0;pulling=true},{passive:true});document.addEventListener("touchmove",function(event){if(!pulling||event.touches.length!==1)return;distance=Math.max(0,event.touches[0].clientY-startY);if(distance<8)return;event.preventDefault();indicator.hidden=false;indicator.classList.add("is-pulling");indicator.classList.toggle("is-ready",distance>=threshold);vincularEstadoLegenda(indicator,(distance>=threshold?"legenda_atendimento_solte_atualizar":"legenda_atendimento_puxe_atualizar"),"");indicator.style.transform="translate(-50%, "+Math.min(38,distance*.35)+"px)"},{passive:false});document.addEventListener("touchend",function(){if(!pulling)return;var refresh=distance>=threshold;pulling=false;if(!refresh){reset();return}indicator.hidden=false;indicator.classList.remove("is-pulling","is-ready");indicator.classList.add("is-refreshing");indicator.style.transform="";vincularEstadoLegenda(indicator,"legenda_atendimento_atualizando","");refreshVisibleData().then(function(){vincularEstadoLegenda(indicator,"legenda_atendimento_atualizado","")}).catch(function(){vincularEstadoLegenda(indicator,"legenda_atendimento_atualizacao_falhou","")}).finally(function(){setTimeout(reset,700)})},{passive:true});document.addEventListener("touchcancel",reset,{passive:true})}
  function showAudioPlayer(button,messageId,url){var audio=document.createElement("audio");audio.controls=true;audio.autoplay=true;audio.preload="metadata";audio.src=url;audio.dataset.messageId=safe(messageId);audio.setAttribute("aria-label",legendaAtendimento("legenda_atendimento_audio_recebido_pelo_whatsapp"));button.replaceWith(audio)}
  async function loadAudio(button,messageId){
    var key=safe(messageId),conversationId=state.selecionada&&state.selecionada.id,cached=state.mediaUrls.get(key);
    if(cached){showAudioPlayer(button,messageId,cached);return}
    button.disabled=true;button.dataset.loading="true";vincularEstadoLegenda(button,"legenda_atendimento_audio_carregando","");
    try{var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/media?message_id="+encodeURIComponent(messageId),{headers:{Authorization:"Bearer "+current.access_token}});if(!response.ok)throw new Error(legendaAtendimento("legenda_atendimento_audio_indisponivel"));var url=URL.createObjectURL(await response.blob());if(!state.selecionada||state.selecionada.id!==conversationId||!button.isConnected){URL.revokeObjectURL(url);return}state.mediaUrls.set(key,url);showAudioPlayer(button,messageId,url)}catch(error){if(button.isConnected){delete button.dataset.loading;button.disabled=false;vincularEstadoLegenda(button,"legenda_atendimento_audio_tentar_novamente","");button.title=error.message||String(error)}}
  }
  function transcriptionText(m){var value=m.transcricao;if(value&&typeof value==="object")value=value.texto||value.text||"";value=safe(value||m.texto||"").trim();return /^\[audio\]$/i.test(value)?"":value}
  function transcriptionFailed(m){var status=safe(m.transcricao_status||m.transcricao_estado||"").toLowerCase();return !!(m.transcricao_erro||m.erro_transcricao||/falh|erro|indispon|exced|bloque/.test(status)||(status&&/conclu|finaliz/.test(status)&&!transcriptionText(m)))}
  function renderAudioContent(item,m){
    var box=item.querySelector(".audio-message");
    if(!box){item.innerHTML="";box=document.createElement("div");box.className="audio-message";item.appendChild(box)}
    var key=safe(m.id),audio=box.querySelector("audio"),button=box.querySelector(".audio-play-button"),cached=state.mediaUrls.get(key);
    if(!audio&&cached){if(button)button.remove();audio=document.createElement("audio");audio.controls=true;audio.preload="metadata";audio.src=cached;audio.dataset.messageId=key;audio.setAttribute("aria-label",legendaAtendimento("legenda_atendimento_audio_recebido_pelo_whatsapp"));box.prepend(audio)}
    if(!audio){if(!button){button=document.createElement("button");button.type="button";button.className="audio-play-button";button.addEventListener("click",function(){loadAudio(button,m.id)});box.prepend(button)}if(button.dataset.loading!=="true"){vincularEstadoLegenda(button,(m.midia_disponivel?"legenda_atendimento_audio_ouvir":"legenda_atendimento_audio_indisponivel"),"");button.disabled=!m.midia_disponivel}}
    var transcript=transcriptionText(m),failed=transcriptionFailed(m),transcription=box.querySelector(".audio-transcription");
    if(!transcription){transcription=document.createElement("div");var label=document.createElement("strong"),paragraph=document.createElement("p");transcription.append(label,paragraph);box.appendChild(transcription)}
    var labelNode=transcription.querySelector("strong"),paragraphNode=transcription.querySelector("p");
    transcription.className="audio-transcription"+(transcript?"":failed?" is-error":" is-pending");
    vincularEstadoLegenda(labelNode,(transcript?"legenda_atendimento_transcricao":(failed?"legenda_atendimento_transcricao_indisponivel":"legenda_atendimento_transcricao")),"");
    if(transcript)renderFormattedText(paragraphNode,transcript);else vincularEstadoLegenda(paragraphNode,(failed?"legenda_atendimento_transcricao_falhou":"legenda_atendimento_transcricao_processando"),"")
  }
  function renderMessageElement(item,m){
    var type=safe(m.tipo||"text").toLowerCase(),key=safe(m.id);
    item.className="message"+(m.direcao==="saida"?" out":"");item.dataset.messageId=key;item.dataset.messageType=type;
    if(type==="audio")renderAudioContent(item,m);else{if(item.querySelector(".audio-message")){releaseMediaUrl(key);item.innerHTML=""}var body=item.querySelector(".message-text");if(!body){body=document.createElement("div");body.className="message-text";item.prepend(body)}renderFormattedText(body,m.texto||("["+type+"]"))}
    var meta=item.querySelector(".message-meta");if(!meta){meta=document.createElement("small");meta.className="message-meta";item.appendChild(meta)}
    meta.innerHTML="";var author=m.autor_tipo==="ia"?legendaAtendimento("legenda_atendimento_ia"):m.autor_tipo==="atendente"?legendaAtendimento("legenda_atendimento_atendente"):"";meta.appendChild(document.createTextNode(author+time(m.criado_em)+" · "));var status=document.createElement("span");status.className="message-status"+(safe(m.status).toLowerCase()==="failed"?" is-error":"");vincularEstadoLegenda(status,chaveEstadoLegenda(LEGENDAS_ESTADOS_MENSAGEM,safe(m.status).toLowerCase()),messageStatusName(m.status));meta.appendChild(status)
  }
  function renderDetail(){
    var data=state.detalhe||{},stream=el("messageStream"),messages=data.mensagens||[],nearBottom=stream.scrollHeight-stream.scrollTop-stream.clientHeight<90,previousScroll=stream.scrollTop,existing=new Map(),used=new Set(),cursor=stream.firstElementChild;
    Array.from(stream.children).forEach(function(item){existing.set(item.dataset.messageId,item)});
    messages.forEach(function(m){var key=safe(m.id),item=existing.get(key);if(!item)item=document.createElement("div");renderMessageElement(item,m);used.add(key);if(item!==cursor)stream.insertBefore(item,cursor);cursor=item.nextElementSibling});
    Array.from(stream.children).forEach(function(item){if(!used.has(item.dataset.messageId)){releaseMediaUrl(item.dataset.messageId);item.remove()}});
    if(nearBottom||messages.length===1)stream.scrollTop=stream.scrollHeight;else stream.scrollTop=previousScroll;
    var notes=el("notesList");desvincularEstadoLegenda(notes);notes.innerHTML="";(data.notas||[]).forEach(function(n){var d=document.createElement("div");d.textContent=n.texto;var small=document.createElement("small");small.textContent=new Date(n.criado_em).toLocaleString("pt-BR");d.appendChild(small);notes.appendChild(d)});if(!notes.children.length)vincularEstadoLegenda(notes,"legenda_atendimento_notas_vazias","");
    var audit=el("auditList");audit.innerHTML="";(data.auditoria||[]).slice(0,8).forEach(function(a){var d=document.createElement("div");d.textContent=safe(a.acao).replaceAll("_"," ");var small=document.createElement("small");small.textContent=new Date(a.criado_em).toLocaleString("pt-BR");d.appendChild(small);audit.appendChild(d)})
  }
  async function takeConversation(){var conversationId=state.selecionada.id,data=await rpc("adm_atendimento_assumir_rpc",{p_conversa:conversationId});if(!data.ok)throw new Error(data.error);var sendError=null;if(data.apresentacao_enviar&&data.apresentacao_texto){try{var current=await session(),response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,text:data.apresentacao_texto})}),sent=await parse(response);if(!sent.ok)throw new Error(sent.error||legendaAtendimento("legenda_atendimento_erro_enviar_apresentacao"))}catch(error){sendError=error}}await loadConversations(true,true);if(sendError)throw new Error(legendaAtendimento("legenda_atendimento_erro_apresentacao_apos_assumir",{erro:sendError.message||String(sendError)}))}
  async function returnConversationToAi(){if(!state.selecionada)return;var conversationId=state.selecionada.id,prepared=await rpc("adm_atendimento_devolver_ia_preparar_rpc",{p_conversa:conversationId});if(!prepared.ok)throw new Error(prepared.error);if(prepared.despedida_enviar&&prepared.despedida_texto){var current=await session(),response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,text:prepared.despedida_texto})}),sent=await parse(response);if(!sent.ok)throw new Error(sent.error||legendaAtendimento("legenda_atendimento_erro_enviar_despedida"))}var data=await rpc("adm_atendimento_devolver_ia_rpc",{p_conversa:conversationId});if(!data.ok)throw new Error(data.error);await loadConversations(true,true)}
  async function toggleConversationAssignment(){if(state.selecionada&&state.selecionada.atendente)return returnConversationToAi();return takeConversation()}
  async function sendMessage(event){event.preventDefault();if(!state.selecionada||!isMine(state.selecionada)||!isFuture(state.selecionada.janela_24h_ate)||state.selecionada.status!=="em_atendimento"){updateComposerState();return}var text=el("messageInput").value.trim();if(!text)return;var send=el("sendButton");send.disabled=true;try{var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:state.selecionada.id,text:text})});var data=await parse(response);if(!data.ok)throw new Error(data.error||legendaAtendimento("legenda_atendimento_erro_enviar"));el("messageInput").value="";await loadConversations(true,true)}finally{updateComposerState()}}
  async function saveNote(event){event.preventDefault();if(!state.selecionada)return;var text=el("noteInput").value.trim();if(!text)return;var data=await rpc("adm_atendimento_nota_salvar_rpc",{p_conversa:state.selecionada.id,p_texto:text});if(!data.ok)throw new Error(data.error);el("noteInput").value="";await selectConversation(state.selecionada)}
  function schedulerDefaultDate(){var date=new Date();date.setDate(date.getDate()+1);date.setHours(9,0,0,0);var offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerLocalDate(value){var date=new Date(value),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerStatusName(value){return {agendada:legendaAtendimento("legenda_atendimento_agendada"),processando:legendaAtendimento("legenda_atendimento_frase_enviando"),concluida:legendaAtendimento("legenda_atendimento_concluida"),cancelada:legendaAtendimento("legenda_atendimento_cancelada")}[value]||safe(value)}
  function schedulerFeedback(message,isError){var box=el("schedulerFeedback");if(typeof message==="function")aplicarTextoAtendimento(box,message);else{textosComplementaresAtendimento.delete(box);box.textContent=message||""}box.classList.toggle("is-error",!!isError)}
  function renderSchedulerContacts(){var wrap=el("schedulerContacts");wrap.innerHTML="";var rows=state.conversas.filter(function(c){return c.canal&&c.canal.tipo==="whatsapp"});rows.forEach(function(c){var label=document.createElement("label");label.className="scheduler-contact";var input=document.createElement("input");input.type="checkbox";input.value=c.id;var text=document.createElement("span");text.textContent=(c.contato.nome||c.contato.telefone)+" · "+(c.contato.telefone||"");label.append(input,text);wrap.appendChild(label)});if(!rows.length){var empty=document.createElement("span");vincularEstadoLegenda(empty,"legenda_atendimento_conversas_whatsapp_vazias","");wrap.appendChild(empty)}}
  function renderSchedulerTemplates(){var select=el("schedulerTemplate"),templates=(state.agendador&&state.agendador.templates)||[];select.innerHTML="";templates.forEach(function(t){var option=document.createElement("option");option.value=t.id;option.textContent=t.nome+" · "+t.idioma+" · "+t.categoria;select.appendChild(option)});var templateRadio=document.querySelector('input[name="schedulerOutsideWindow"][value="template"]');templateRadio.disabled=!templates.length;aplicarTextoAtendimento(el("schedulerTemplateHint"),function(){return templates.length?legendaAtendimento("legenda_atendimento_somente_templates_com_status_aprovado_pela_meta_sao_exibidos"):legendaAtendimento("legenda_atendimento_nenhum_template_aprovado_esta_disponivel_cadastre_e_sincronize_um_template_antes_de")});if(!templates.length&&templateRadio.checked){document.querySelector('input[name="schedulerOutsideWindow"][value="nao_enviar"]').checked=true}toggleSchedulerOutsideWindow()}
  function campaignCard(c){var card=document.createElement("article");card.className="scheduler-campaign";var header=document.createElement("header"),title=document.createElement("div"),h4=document.createElement("h4"),date=document.createElement("time"),status=document.createElement("span");h4.textContent=c.nome;date.textContent=new Date(c.agendada_para).toLocaleString("pt-BR");status.className="scheduler-status"+(c.status==="concluida"?" is-complete":c.status==="cancelada"?" is-cancelled":"");aplicarTextoAtendimento(status,function(){return schedulerStatusName(c.status)});title.append(h4,date);header.append(title,status);var instruction=document.createElement("p");instruction.textContent=c.instrucao_ia;var counts=document.createElement("div");counts.className="scheduler-counts";[["legenda_atendimento_destinatarios",c.total_destinatarios],["legenda_atendimento_frase_enviadas",c.total_enviados],["legenda_atendimento_frase_ignoradas",c.total_ignorados],["legenda_atendimento_frase_falhas",c.total_falhas]].forEach(function(item){var span=document.createElement("span");aplicarTextoAtendimento(span,function(){return legendaAtendimento(item[0])+": "+item[1]});counts.appendChild(span)});var footer=document.createElement("footer");if(c.status==="agendada"){var edit=document.createElement("button");edit.type="button";edit.className="btn btn-ghost btn-small";aplicarTextoAtendimento(edit,function(){return legendaAtendimento("legenda_atendimento_editar")});edit.addEventListener("click",function(){startEditScheduledCampaign(c)});footer.appendChild(edit)}if(c.status==="agendada"||c.status==="processando"){var cancel=document.createElement("button");cancel.type="button";cancel.className="btn btn-ghost btn-small";aplicarTextoAtendimento(cancel,function(){return legendaAtendimento("legenda_atendimento_cancelar")});cancel.addEventListener("click",function(){cancelScheduledCampaign(c.id,c.nome).catch(function(error){schedulerFeedback(error.message||String(error),true)})});footer.appendChild(cancel)}card.append(header,instruction,counts,footer);return card}
  function renderSchedulerCampaigns(){var wrap=el("schedulerCampaigns"),campaigns=(state.agendador&&state.agendador.campanhas)||[];wrap.innerHTML="";if(!campaigns.length){var empty=document.createElement("p");vincularEstadoLegenda(empty,"legenda_atendimento_programacoes_vazias","");wrap.appendChild(empty);return}campaigns.forEach(function(c){wrap.appendChild(campaignCard(c))})}
  async function loadScheduler(){schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_carregando_programacoes")});var data=await rpc("adm_atendimento_agendador_contexto_rpc",{});if(!data.ok)throw new Error(data.error);state.agendador=data;renderSchedulerTemplates();renderSchedulerCampaigns();schedulerFeedback("")}
  async function openScheduler(){el("schedulerDate").value=el("schedulerDate").value||schedulerDefaultDate();renderSchedulerContacts();var dialog=el("schedulerDialog");if(!dialog.open)dialog.showModal();try{await loadScheduler()}catch(error){schedulerFeedback(error.message||String(error),true)}}
  function resetSchedulerForm(){state.editCampaign=null;el("schedulerForm").reset();el("schedulerDate").value=schedulerDefaultDate();document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=false});el("schedulerAudienceHint").textContent="";aplicarTextoAtendimento(el("schedulerSubmit"),function(){return legendaAtendimento("legenda_atendimento_programar_envio")});aplicarTextoAtendimento(el("schedulerCancel"),function(){return legendaAtendimento("legenda_atendimento_agendador_fechar")});toggleSchedulerAudience();toggleSchedulerOutsideWindow();renderSchedulerContacts()}
  function closeScheduler(){resetSchedulerForm();if(el("schedulerDialog").open)el("schedulerDialog").close()}
  function cancelSchedulerForm(){if(state.editCampaign){resetSchedulerForm();schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_edicao_cancelada")})}else closeScheduler()}
  function startEditScheduledCampaign(c){state.editCampaign=c;el("schedulerName").value=c.nome||"";el("schedulerDate").value=schedulerLocalDate(c.agendada_para);el("schedulerInstruction").value=c.instrucao_ia||"";document.querySelector('input[name="schedulerOutsideWindow"][value="'+c.fora_janela_acao+'"]').checked=true;if(c.template&&c.template.id)el("schedulerTemplate").value=c.template.id;document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=true});el("schedulerContacts").hidden=true;aplicarTextoAtendimento(el("schedulerAudienceHint"),function(){return legendaAtendimento("legenda_atendimento_frase_destinatarios_preservados_quantidade",{quantidade:c.total_destinatarios})});aplicarTextoAtendimento(el("schedulerSubmit"),function(){return legendaAtendimento("legenda_atendimento_salvar_alteracoes")});aplicarTextoAtendimento(el("schedulerCancel"),function(){return legendaAtendimento("legenda_atendimento_cancelar_edicao")});toggleSchedulerOutsideWindow();schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_frase_editando_nome",{nome:c.nome})});el("schedulerName").focus()}
  function toggleSchedulerAudience(){var selected=document.querySelector('input[name="schedulerAudience"]:checked');el("schedulerContacts").hidden=!selected||selected.value!=="selecionados"}
  function toggleSchedulerOutsideWindow(){var selected=document.querySelector('input[name="schedulerOutsideWindow"]:checked');el("schedulerTemplateField").hidden=!selected||selected.value!=="template"}
  async function createScheduledCampaign(event){event.preventDefault();schedulerFeedback("");var audience=document.querySelector('input[name="schedulerAudience"]:checked').value,outside=document.querySelector('input[name="schedulerOutsideWindow"]:checked').value,selected=Array.from(el("schedulerContacts").querySelectorAll('input[type="checkbox"]:checked')).map(function(input){return Number(input.value)});if(!state.editCampaign&&audience==="selecionados"&&!selected.length){schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_selecione_pelo_menos_um_contato")},true);return}var localDate=el("schedulerDate").value;if(!localDate){schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_escolha_a_data_e_o_horario")},true);return}var submit=el("schedulerSubmit"),editing=state.editCampaign;submit.disabled=true;aplicarTextoAtendimento(submit,function(){return editing?legendaAtendimento("legenda_atendimento_agendador_salvando"):legendaAtendimento("legenda_atendimento_agendador_programando")});try{var common={p_nome:el("schedulerName").value.trim(),p_instrucao_ia:el("schedulerInstruction").value.trim(),p_agendada_para:new Date(localDate).toISOString(),p_fora_janela_acao:outside,p_template:outside==="template"?Number(el("schedulerTemplate").value):null},data;if(editing){common.p_campanha=editing.id;data=await rpc("adm_atendimento_agendamento_editar_rpc",common)}else{common.p_publico_tipo=audience;common.p_conversas=selected;data=await rpc("adm_atendimento_agendamento_criar_rpc",common)}if(!data.ok)throw new Error(data.error);resetSchedulerForm();await loadScheduler();schedulerFeedback(function(){return editing?legendaAtendimento("legenda_atendimento_programacao_atualizada_com_sucesso"):legendaAtendimento("legenda_atendimento_agendador_programacao_criada_quantidade",{quantidade:data.total_destinatarios})}) }catch(error){schedulerFeedback(error.message||String(error),true)}finally{submit.disabled=false;aplicarTextoAtendimento(submit,function(){return state.editCampaign?legendaAtendimento("legenda_atendimento_salvar_alteracoes"):legendaAtendimento("legenda_atendimento_programar_envio")})}}
  async function cancelScheduledCampaign(id,name){if(!confirm(legendaAtendimento("legenda_atendimento_cancelar_a_programacao")+name+legendaAtendimento("legenda_atendimento_mensagens_ja_enviadas_nao_serao_afetadas")))return;var data=await rpc("adm_atendimento_agendamento_cancelar_rpc",{p_campanha:id});if(!data.ok)throw new Error(data.error);schedulerFeedback(function(){return legendaAtendimento("legenda_atendimento_programacao_cancelada")});await loadScheduler()}
  async function init(){try{state.session=readSession();if(!state.session){location.href="../";return}var admin=await rpc("adm_contexto_rpc",{});if(!admin.ok||!Array.isArray(admin.areas)||(admin.areas.indexOf("atendimento")<0&&admin.areas.indexOf("admin")<0))throw new Error(legendaAtendimento("legenda_atendimento_erro_sem_permissao"));state.contexto=await rpc("adm_atendimento_contexto_rpc",{});if(!state.contexto.ok)throw new Error(state.contexto.error);el("adminIdentity").textContent=(state.contexto.atendente&&state.contexto.atendente.nome)||(state.session.user&&state.session.user.email)||"Turbo Tiger";setAttendantStatus((state.contexto.atendente&&state.contexto.atendente.status)||"offline");el("agentStatus").disabled=!currentAttendant();el("agentStatus").addEventListener("change",function(){saveAttendantStatus()});state.serverUrl=await rpc("app_config_buscar_rpc",{p_categoria:"turbotiger_urls",p_tipo:"servidor_whatsapp"});if(typeof state.serverUrl!=="string"||!state.serverUrl)throw new Error(legendaAtendimento("legenda_atendimento_erro_servidor_configuracao"));await initializePulse();await loadConversations();initPullToRefresh();setInterval(syncAutomatically,3000);setInterval(updateSelectedTimeState,1000);document.addEventListener("visibilitychange",function(){if(!document.hidden)syncAutomatically()});window.addEventListener("beforeunload",releaseAllMediaUrls)}catch(error){el("pageStatus").textContent=error.message||String(error);el("pageStatus").classList.add("is-error")}}
  document.querySelectorAll(".queue-button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".queue-button").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.setor=b.dataset.sector;loadConversations().catch(alert)})});document.querySelectorAll(".channel-tab").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".channel-tab").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.canal=b.dataset.channel;renderList()})});document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.addEventListener("change",toggleSchedulerAudience)});document.querySelectorAll('input[name="schedulerOutsideWindow"]').forEach(function(input){input.addEventListener("change",toggleSchedulerOutsideWindow)});el("conversationSearch").addEventListener("input",renderList);el("reloadButton").addEventListener("click",function(){loadConversations().catch(alert)});el("takeConversationButton").addEventListener("click",function(){toggleConversationAssignment().catch(alert)});el("messageForm").addEventListener("submit",function(e){sendMessage(e).catch(alert)});el("noteForm").addEventListener("submit",function(e){saveNote(e).catch(alert)});el("schedulerButton").addEventListener("click",function(){openScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerClose").addEventListener("click",closeScheduler);el("schedulerCancel").addEventListener("click",cancelSchedulerForm);el("schedulerReload").addEventListener("click",function(){loadScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerForm").addEventListener("submit",createScheduledCampaign);el("schedulerDialog").addEventListener("click",function(event){if(event.target===el("schedulerDialog"))closeScheduler()});el("logoutButton").addEventListener("click",function(){clearSession();location.href="../"});el("templatesButton").addEventListener("click",function(){alert(legendaAtendimento("legenda_atendimento_gestao_de_templates_sera_aberta_na_proxima_etapa_de_configuracao_da_meta"))});el("chooseTemplateButton").addEventListener("click",function(){alert(legendaAtendimento("legenda_atendimento_selecione_um_template_aprovado_quando_a_janela_de_24_horas_estiver_fechada"))});el("settingsButton").addEventListener("click",function(){alert(legendaAtendimento("legenda_atendimento_configuracoes_de_canais_setores_e_atendentes_sao_restritas_a_supervisao"))});init();
})();
