(function () {
  "use strict";

  var CONFIG={supabaseUrl:"https://jzqgudmvquokizvgehow.supabase.co",apiKey:"sb_publishable_eAPW_Kg8SLYpL43JVe104Q__qvEbyDU",sessionKey:"tt_admin_session_v1"};
  var state={session:null,contexto:null,conversas:[],selecionada:null,detalhe:null,setor:"",canal:"",serverUrl:"",syncing:false,mediaUrls:new Map(),pulseToken:null,pulseAvailable:true,pulseRetryAt:0,agendador:null,editCampaign:null};
  function el(id){return document.getElementById(id)}
  function readSession(){try{return JSON.parse(localStorage.getItem(CONFIG.sessionKey)||"null")}catch(e){return null}}
  function saveSession(value){state.session=value;localStorage.setItem(CONFIG.sessionKey,JSON.stringify(value))}
  function clearSession(){state.session=null;localStorage.removeItem(CONFIG.sessionKey)}
  async function parse(response){var text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw new Error((data&&(data.message||data.error))||"Falha de conexão");return data}
  async function session(){if(!state.session)state.session=readSession();if(!state.session||!state.session.access_token)return null;if(!state.session.expires_at||state.session.expires_at>Date.now()+60000)return state.session;var response=await fetch(CONFIG.supabaseUrl+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:CONFIG.apiKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:state.session.refresh_token})});var data=await parse(response);saveSession({access_token:data.access_token,refresh_token:data.refresh_token||state.session.refresh_token,expires_at:Date.now()+Number(data.expires_in||3600)*1000,user:data.user||state.session.user});return state.session}
  async function rpc(name,payload){var current=await session();if(!current){location.href="../";throw new Error("Sessão expirada")};return parse(await fetch(CONFIG.supabaseUrl+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:CONFIG.apiKey,Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify(payload||{})}))}
  function safe(value){return String(value==null?"":value)}
  function initials(name){var text=safe(name||"TT").normalize("NFC").trim(),first=text.match(/^[\p{L}\p{N}]+/u),parts=text.match(/[\p{L}\p{N}]+/gu)||[];if(!parts.length)return"TT";var firstLetters=Array.from(parts[0]);if((first&&/^\s+[^\p{L}\p{N}]/u.test(text.slice(first[0].length)))||parts.length===1)return firstLetters.slice(0,2).join("").toLocaleUpperCase("pt-BR");return(firstLetters[0]+Array.from(parts[1])[0]).toLocaleUpperCase("pt-BR")}
  function titleName(name){return safe(name).normalize("NFC").trim().toLocaleLowerCase("pt-BR").replace(/(^|\s)([\p{L}])/gu,function(_,space,letter){return space+letter.toLocaleUpperCase("pt-BR")})}
  function renderAvatar(target,url,name){target.innerHTML="";target.style.overflow="hidden";var fallback=initials(name);target.textContent=fallback;if(!url)return;var image=document.createElement("img");image.alt="Foto de "+safe(name||"contato");image.loading="lazy";image.referrerPolicy="no-referrer";image.style.cssText="width:100%;height:100%;display:block;object-fit:cover";image.addEventListener("load",function(){target.textContent="";target.appendChild(image)});image.addEventListener("error",function(){target.textContent=fallback});image.src=url}
  function time(value){if(!value)return "—";return new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}
  function remaining(value){if(!value)return "—";var seconds=Math.max(0,Math.floor((new Date(value)-Date.now())/1000)),h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return (h<10?"0":"")+h+":"+(m<10?"0":"")+m}
  function channelName(value){return {whatsapp:"WhatsApp",instagram:"Instagram",messenger:"Messenger"}[value]||safe(value)}
  function statusName(value){return {nova:"Nova",triagem_ia:"IA em triagem",aguardando:"Aguardando humano",em_atendimento:"Em atendimento",pendente_cliente:"Aguardando cliente",resolvida:"Resolvida",fechada:"Fechada"}[value]||safe(value)}
  function messageStatusName(value){return {received:"recebida",recebida:"recebida",accepted:"aceita",sent:"enviada",delivered:"entregue",read:"lida",failed:"falhou",pending:"enviando",processing:"processando"}[safe(value).toLowerCase()]||safe(value).replaceAll("_"," ")}
  function isFuture(value){return !!value&&!Number.isNaN(new Date(value).getTime())&&new Date(value).getTime()>Date.now()}
  function currentAttendant(){return state.contexto&&state.contexto.atendente}
  function isMine(c){var attendant=currentAttendant();return !!(c&&c.atendente&&attendant&&Number(c.atendente.id)===Number(attendant.id))}
  function releaseMediaUrl(messageId){var key=safe(messageId),url=state.mediaUrls.get(key);if(url){URL.revokeObjectURL(url);state.mediaUrls.delete(key)}}
  function releaseAllMediaUrls(){state.mediaUrls.forEach(function(url){URL.revokeObjectURL(url)});state.mediaUrls.clear()}
  function setAttendantStatus(status){var value=["online","ocupado","pausa","offline"].indexOf(status)>=0?status:"offline",select=el("agentStatus"),label=select&&select.closest(".agent-status");if(select)select.value=value;if(label)label.dataset.status=value;if(state.contexto&&state.contexto.atendente)state.contexto.atendente.status=value}
  async function saveAttendantStatus(){var select=el("agentStatus"),previous=(state.contexto&&state.contexto.atendente&&state.contexto.atendente.status)||"offline",wanted=select.value;select.disabled=true;try{var data=await rpc("adm_atendimento_atendente_status_rpc",{p_status:wanted});if(!data||!data.ok)throw new Error((data&&data.error)||"Não foi possível atualizar seu status");setAttendantStatus(data.status||wanted);el("pageStatus").classList.remove("is-error");el("pageStatus").textContent="Status atualizado: "+titleName(data.status||wanted)}catch(error){setAttendantStatus(previous);el("pageStatus").textContent=error.message||String(error);el("pageStatus").classList.add("is-error")}finally{select.disabled=!currentAttendant()}}
  function createLink(url,label){var link=document.createElement("a");link.className="message-link";link.href=url;link.target="_blank";link.rel="noopener noreferrer";link.textContent=label||url;return link}
  function appendPlainUrl(target,raw){var url=raw,trailing="";while(/[.,!?;:\]\}]$/.test(url)){trailing=url.slice(-1)+trailing;url=url.slice(0,-1)}target.appendChild(createLink(url,url));if(trailing)target.appendChild(document.createTextNode(trailing))}
  function renderFormattedText(target,value){target.innerHTML="";var source=safe(value),pattern=/\[([^\]\n]{1,240})\]\((https?:\/\/[^\s)]+)\)|(https?:\/\/[^\s<]+)|\*([^*\n]+)\*/g,last=0,match;while((match=pattern.exec(source))!==null){if(match.index>last)target.appendChild(document.createTextNode(source.slice(last,match.index)));if(match[2])target.appendChild(createLink(match[2],match[1]));else if(match[3])appendPlainUrl(target,match[3]);else{var strong=document.createElement("strong");strong.textContent=match[4];target.appendChild(strong)}last=pattern.lastIndex}if(last<source.length)target.appendChild(document.createTextNode(source.slice(last)))}
  function clearSelection(){releaseAllMediaUrls();state.selecionada=null;state.detalhe=null;el("chatEmpty").hidden=false;el("chatContent").hidden=true;el("customerEmpty").hidden=false;el("customerContent").hidden=true;el("messageStream").innerHTML="";el("messageInput").value="";updateComposerState()}
  function updateComposerState(){var c=state.selecionada,attendant=currentAttendant(),open=!!(c&&isFuture(c.janela_24h_ate)),mine=isMine(c),other=!!(c&&c.atendente&&!mine),inService=!!(c&&c.status==="em_atendimento"),enabled=!!(c&&attendant&&open&&mine&&inService),input=el("messageInput"),send=el("sendButton"),template=el("chooseTemplateButton"),hint=el("composerHint");input.disabled=!enabled;send.disabled=!enabled;template.disabled=!(c&&attendant&&!open&&mine&&inService);if(!c)hint.textContent="Assuma uma conversa para responder";else if(other)hint.textContent="Conversa em atendimento por "+titleName(c.atendente.nome||"outro atendente")+".";else if(!mine)hint.textContent="Assuma a conversa para responder.";else if(!inService)hint.textContent="A conversa não está em atendimento.";else if(!open)hint.textContent="Janela de atendimento encerrada. Use um template aprovado.";else hint.textContent="Dentro da janela de atendimento"}
  function updateSelectedTimeState(){var c=state.selecionada;if(!c)return;el("detailWindow").textContent=isFuture(c.janela_24h_ate)?"Aberta · "+remaining(c.janela_24h_ate):"Fechada";el("windowStatus").textContent=isFuture(c.janela_24h_ate)?"Janela "+remaining(c.janela_24h_ate):"Janela fechada";var sla=el("slaStatus");if(c.status==="aguardando"&&c.primeira_resposta_ate)sla.textContent=isFuture(c.primeira_resposta_ate)?"SLA humano "+remaining(c.primeira_resposta_ate):"SLA humano vencido";else if(c.status==="em_atendimento")sla.textContent="SLA humano atendido";else sla.textContent="SLA humano —";updateComposerState()}
  function renderConversationHeader(c){if(!c)return;el("chatContact").textContent=c.contato.nome||c.contato.telefone;el("chatMeta").textContent=channelName(c.canal.tipo)+" · "+c.contato.telefone;el("customerName").textContent=c.contato.nome||"Contato";el("customerPhone").textContent=c.contato.telefone||"";renderAvatar(el("chatAvatar"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);renderAvatar(el("customerAvatar"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);el("detailChannel").textContent=channelName(c.canal.tipo);el("detailSector").textContent=c.setor.nome;var attendantName=c.atendente?titleName(c.atendente.nome):"",assignmentButton=el("takeConversationButton"),mine=isMine(c);el("detailAssignment").textContent=c.atendente?attendantName:statusName(c.status);assignmentButton.disabled=!!c.atendente&&!mine;assignmentButton.textContent=c.atendente?(mine?"Com "+attendantName+" · Voltar para IA":"Com "+attendantName):"Assumir conversa";assignmentButton.style.backgroundColor=c.atendente?"#168a4a":"";assignmentButton.style.borderColor=c.atendente?"#168a4a":"";assignmentButton.style.color=c.atendente?"#fff":"";var banner=el("aiBanner");banner.hidden=!c.ia_ativa||c.status==="em_atendimento";banner.textContent=c.status==="aguardando"?"Aguardando atendimento humano. A IA permanece apenas na recepção durante a espera.":"A IA está fazendo a triagem inicial. Assuma a conversa para interromper a automação.";updateSelectedTimeState()}
  function renderList(){
    var query=el("conversationSearch").value.trim().toLocaleLowerCase("pt-BR");
    var rows=state.conversas.filter(function(c){return(!state.canal||c.canal.tipo===state.canal)&&(!query||safe(c.contato.nome+" "+c.contato.telefone+" "+c.ultima_mensagem).toLocaleLowerCase("pt-BR").indexOf(query)>=0)});
    if(state.selecionada&&!rows.some(function(c){return c.id===state.selecionada.id}))clearSelection();
    el("countAll").textContent=state.conversas.length;
    document.querySelectorAll(".queue-button[data-sector]").forEach(function(btn){var key=btn.dataset.sector,count=key?state.conversas.filter(function(c){return c.setor.chave===key}).length:state.conversas.length;btn.querySelector("span").textContent=count});
    var wrap=el("conversationList");wrap.innerHTML="";
    if(!rows.length){wrap.innerHTML='<div class="empty-list">Nenhuma conversa nesta fila.</div>';return}
    rows.forEach(function(c){var b=document.createElement("button");b.type="button";b.className="conversation-row"+(state.selecionada&&state.selecionada.id===c.id?" is-active":"");b.innerHTML='<span class="channel-mark"></span><span class="conversation-copy"><strong></strong><span class="sector"></span><span class="preview"></span></span><span class="conversation-side"><time></time><span class="conversation-state"></span></span>';renderAvatar(b.querySelector(".channel-mark"),c.contato.foto_perfil_url,c.contato.nome||c.contato.telefone);b.querySelector("strong").textContent=c.contato.nome||c.contato.telefone;b.querySelector(".sector").textContent=c.setor.nome+" · "+channelName(c.canal.tipo);b.querySelector(".preview").textContent=c.ultima_mensagem||"Sem mensagem de texto";b.querySelector("time").textContent=time(c.ultima_mensagem_em);var status=b.querySelector(".conversation-state");status.textContent=statusName(c.status);if(c.status==="aguardando"){status.style.background="#fee2e2";status.style.color="#b42318"}else if(c.status==="em_atendimento"){status.style.background="#dcfce7";status.style.color="#168a4a"}b.addEventListener("click",function(){selectConversation(c)});wrap.appendChild(b)})
  }
  async function loadConversations(silent,forceDetail){
    if(!silent)el("pageStatus").textContent="Atualizando";
    var selectedId=state.selecionada&&state.selecionada.id,selectedVersion=state.selecionada&&state.selecionada.versao;
    var data=await rpc("adm_atendimento_conversas_rpc",{p_setor:state.setor||null,p_status:null,p_limite:100});
    if(!data.ok)throw new Error(data.error);
    state.conversas=data.conversas||[];
    if(selectedId){
      var updated=state.conversas.find(function(c){return c.id===selectedId});
      if(updated){state.selecionada=updated;renderConversationHeader(updated);if(forceDetail||!silent||updated.versao!==selectedVersion)await refreshConversationDetail()}
      else clearSelection()
    }
    renderList();
    el("pageStatus").classList.remove("is-error");
    el("pageStatus").textContent=state.conversas.length+" conversa(s)"
  }
  async function selectConversation(c){
    var changed=!state.selecionada||state.selecionada.id!==c.id;
    if(changed){releaseAllMediaUrls();state.detalhe=null;el("messageStream").innerHTML="";el("messageInput").value=""}
    state.selecionada=c;
    el("chatEmpty").hidden=true;el("chatContent").hidden=false;el("customerEmpty").hidden=true;el("customerContent").hidden=false;
    renderConversationHeader(c);renderList();await refreshConversationDetail()
  }
  async function refreshConversationDetail(){if(!state.selecionada)return;var selectedId=state.selecionada.id;var data=await rpc("adm_atendimento_conversa_rpc",{p_conversa:selectedId});if(!data||!data.ok)throw new Error((data&&data.error)||"Não foi possível atualizar a conversa");if(!state.selecionada||state.selecionada.id!==selectedId)return;state.detalhe=data;renderDetail()}
  async function readPulse(){var data=await rpc("adm_atendimento_pulso_rpc",{});if(!data||!data.ok||data.token==null)throw new Error((data&&data.error)||"pulso_indisponivel");return safe(data.token)}
  async function initializePulse(){try{state.pulseToken=await readPulse();state.pulseAvailable=true;state.pulseRetryAt=0}catch(error){state.pulseAvailable=false;state.pulseRetryAt=Date.now()+60000}}
  async function syncAutomatically(){
    if(state.syncing||document.hidden)return;
    state.syncing=true;
    try{
      if(state.pulseAvailable){
        try{var token=await readPulse();if(state.pulseToken!==token){state.pulseToken=token;await loadConversations(true,true)}}catch(error){state.pulseAvailable=false;state.pulseRetryAt=Date.now()+60000;await loadConversations(true,true)}
      }else if(Date.now()>=state.pulseRetryAt){
        try{state.pulseToken=await readPulse();state.pulseAvailable=true;state.pulseRetryAt=0;await loadConversations(true,true)}catch(error){state.pulseRetryAt=Date.now()+60000;await loadConversations(true,true)}
      }else await loadConversations(true,true)
    }catch(error){el("pageStatus").textContent="Reconectando automaticamente";el("pageStatus").classList.add("is-error")}
    finally{state.syncing=false}
  }
  function showAudioPlayer(button,messageId,url){var audio=document.createElement("audio");audio.controls=true;audio.autoplay=true;audio.preload="metadata";audio.src=url;audio.dataset.messageId=safe(messageId);audio.setAttribute("aria-label","Áudio recebido pelo WhatsApp");button.replaceWith(audio)}
  async function loadAudio(button,messageId){
    var key=safe(messageId),conversationId=state.selecionada&&state.selecionada.id,cached=state.mediaUrls.get(key);
    if(cached){showAudioPlayer(button,messageId,cached);return}
    button.disabled=true;button.dataset.loading="true";button.textContent="Carregando áudio...";
    try{var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/media?message_id="+encodeURIComponent(messageId),{headers:{Authorization:"Bearer "+current.access_token}});if(!response.ok)throw new Error("Áudio indisponível");var url=URL.createObjectURL(await response.blob());if(!state.selecionada||state.selecionada.id!==conversationId||!button.isConnected){URL.revokeObjectURL(url);return}state.mediaUrls.set(key,url);showAudioPlayer(button,messageId,url)}catch(error){if(button.isConnected){delete button.dataset.loading;button.disabled=false;button.textContent="Tentar ouvir novamente";button.title=error.message||String(error)}}
  }
  function transcriptionText(m){var value=m.transcricao;if(value&&typeof value==="object")value=value.texto||value.text||"";value=safe(value||m.texto||"").trim();return /^\[audio\]$/i.test(value)?"":value}
  function transcriptionFailed(m){var status=safe(m.transcricao_status||m.transcricao_estado||"").toLowerCase();return !!(m.transcricao_erro||m.erro_transcricao||/falh|erro|indispon|exced|bloque/.test(status)||(status&&/conclu|finaliz/.test(status)&&!transcriptionText(m)))}
  function renderAudioContent(item,m){
    var box=item.querySelector(".audio-message");
    if(!box){item.innerHTML="";box=document.createElement("div");box.className="audio-message";item.appendChild(box)}
    var key=safe(m.id),audio=box.querySelector("audio"),button=box.querySelector(".audio-play-button"),cached=state.mediaUrls.get(key);
    if(!audio&&cached){if(button)button.remove();audio=document.createElement("audio");audio.controls=true;audio.preload="metadata";audio.src=cached;audio.dataset.messageId=key;audio.setAttribute("aria-label","Áudio recebido pelo WhatsApp");box.prepend(audio)}
    if(!audio){if(!button){button=document.createElement("button");button.type="button";button.className="audio-play-button";button.addEventListener("click",function(){loadAudio(button,m.id)});box.prepend(button)}if(button.dataset.loading!=="true"){button.textContent=m.midia_disponivel?"▶ Ouvir áudio":"Áudio indisponível";button.disabled=!m.midia_disponivel}}
    var transcript=transcriptionText(m),failed=transcriptionFailed(m),transcription=box.querySelector(".audio-transcription");
    if(!transcription){transcription=document.createElement("div");var label=document.createElement("strong"),paragraph=document.createElement("p");transcription.append(label,paragraph);box.appendChild(transcription)}
    var labelNode=transcription.querySelector("strong"),paragraphNode=transcription.querySelector("p");
    transcription.className="audio-transcription"+(transcript?"":failed?" is-error":" is-pending");
    labelNode.textContent=transcript?"Transcrição":failed?"Transcrição indisponível":"Transcrição";
    if(transcript)renderFormattedText(paragraphNode,transcript);else paragraphNode.textContent=failed?"Não foi possível transcrever este áudio.":"Transcrevendo áudio..."
  }
  function renderMessageElement(item,m){
    var type=safe(m.tipo||"text").toLowerCase(),key=safe(m.id);
    item.className="message"+(m.direcao==="saida"?" out":"");item.dataset.messageId=key;item.dataset.messageType=type;
    if(type==="audio")renderAudioContent(item,m);else{if(item.querySelector(".audio-message")){releaseMediaUrl(key);item.innerHTML=""}var body=item.querySelector(".message-text");if(!body){body=document.createElement("div");body.className="message-text";item.prepend(body)}renderFormattedText(body,m.texto||("["+type+"]"))}
    var meta=item.querySelector(".message-meta");if(!meta){meta=document.createElement("small");meta.className="message-meta";item.appendChild(meta)}
    meta.innerHTML="";var author=m.autor_tipo==="ia"?"IA · ":m.autor_tipo==="atendente"?"Atendente · ":"";meta.appendChild(document.createTextNode(author+time(m.criado_em)+" · "));var status=document.createElement("span");status.className="message-status"+(safe(m.status).toLowerCase()==="failed"?" is-error":"");status.textContent=messageStatusName(m.status);meta.appendChild(status)
  }
  function renderDetail(){
    var data=state.detalhe||{},stream=el("messageStream"),messages=data.mensagens||[],nearBottom=stream.scrollHeight-stream.scrollTop-stream.clientHeight<90,previousScroll=stream.scrollTop,existing=new Map(),used=new Set(),cursor=stream.firstElementChild;
    Array.from(stream.children).forEach(function(item){existing.set(item.dataset.messageId,item)});
    messages.forEach(function(m){var key=safe(m.id),item=existing.get(key);if(!item)item=document.createElement("div");renderMessageElement(item,m);used.add(key);if(item!==cursor)stream.insertBefore(item,cursor);cursor=item.nextElementSibling});
    Array.from(stream.children).forEach(function(item){if(!used.has(item.dataset.messageId)){releaseMediaUrl(item.dataset.messageId);item.remove()}});
    if(nearBottom||messages.length===1)stream.scrollTop=stream.scrollHeight;else stream.scrollTop=previousScroll;
    var notes=el("notesList");notes.innerHTML="";(data.notas||[]).forEach(function(n){var d=document.createElement("div");d.textContent=n.texto;var small=document.createElement("small");small.textContent=new Date(n.criado_em).toLocaleString("pt-BR");d.appendChild(small);notes.appendChild(d)});if(!notes.children.length)notes.textContent="Nenhuma nota interna.";
    var audit=el("auditList");audit.innerHTML="";(data.auditoria||[]).slice(0,8).forEach(function(a){var d=document.createElement("div");d.textContent=safe(a.acao).replaceAll("_"," ");var small=document.createElement("small");small.textContent=new Date(a.criado_em).toLocaleString("pt-BR");d.appendChild(small);audit.appendChild(d)})
  }
  async function takeConversation(){var conversationId=state.selecionada.id,data=await rpc("adm_atendimento_assumir_rpc",{p_conversa:conversationId});if(!data.ok)throw new Error(data.error);var sendError=null;if(data.apresentacao_enviar&&data.apresentacao_texto){try{var current=await session(),response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:conversationId,text:data.apresentacao_texto})}),sent=await parse(response);if(!sent.ok)throw new Error(sent.error||"Não foi possível enviar a apresentação")}catch(error){sendError=error}}await loadConversations(true,true);if(sendError)throw new Error("A conversa foi assumida, mas a apresentação automática não foi enviada: "+(sendError.message||String(sendError)))}
  async function returnConversationToAi(){if(!state.selecionada)return;var data=await rpc("adm_atendimento_devolver_ia_rpc",{p_conversa:state.selecionada.id});if(!data.ok)throw new Error(data.error);await loadConversations(true,true)}
  async function toggleConversationAssignment(){if(state.selecionada&&state.selecionada.atendente)return returnConversationToAi();return takeConversation()}
  async function sendMessage(event){event.preventDefault();if(!state.selecionada||!isMine(state.selecionada)||!isFuture(state.selecionada.janela_24h_ate)||state.selecionada.status!=="em_atendimento"){updateComposerState();return}var text=el("messageInput").value.trim();if(!text)return;var send=el("sendButton");send.disabled=true;try{var current=await session();var response=await fetch(state.serverUrl.replace(/\/$/,"")+"/atendimento/send",{method:"POST",headers:{Authorization:"Bearer "+current.access_token,"Content-Type":"application/json"},body:JSON.stringify({conversation_id:state.selecionada.id,text:text})});var data=await parse(response);if(!data.ok)throw new Error(data.error||"Não foi possível enviar");el("messageInput").value="";await loadConversations(true,true)}finally{updateComposerState()}}
  async function saveNote(event){event.preventDefault();if(!state.selecionada)return;var text=el("noteInput").value.trim();if(!text)return;var data=await rpc("adm_atendimento_nota_salvar_rpc",{p_conversa:state.selecionada.id,p_texto:text});if(!data.ok)throw new Error(data.error);el("noteInput").value="";await selectConversation(state.selecionada)}
  function schedulerDefaultDate(){var date=new Date();date.setDate(date.getDate()+1);date.setHours(9,0,0,0);var offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerLocalDate(value){var date=new Date(value),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
  function schedulerStatusName(value){return {agendada:"Agendada",processando:"Enviando",concluida:"Concluída",cancelada:"Cancelada"}[value]||safe(value)}
  function schedulerFeedback(message,isError){var box=el("schedulerFeedback");box.textContent=message||"";box.classList.toggle("is-error",!!isError)}
  function renderSchedulerContacts(){var wrap=el("schedulerContacts");wrap.innerHTML="";var rows=state.conversas.filter(function(c){return c.canal&&c.canal.tipo==="whatsapp"});rows.forEach(function(c){var label=document.createElement("label");label.className="scheduler-contact";var input=document.createElement("input");input.type="checkbox";input.value=c.id;var text=document.createElement("span");text.textContent=(c.contato.nome||c.contato.telefone)+" · "+(c.contato.telefone||"");label.append(input,text);wrap.appendChild(label)});if(!rows.length){var empty=document.createElement("span");empty.textContent="Nenhuma conversa de WhatsApp carregada.";wrap.appendChild(empty)}}
  function renderSchedulerTemplates(){var select=el("schedulerTemplate"),templates=(state.agendador&&state.agendador.templates)||[];select.innerHTML="";templates.forEach(function(t){var option=document.createElement("option");option.value=t.id;option.textContent=t.nome+" · "+t.idioma+" · "+t.categoria;select.appendChild(option)});var templateRadio=document.querySelector('input[name="schedulerOutsideWindow"][value="template"]');templateRadio.disabled=!templates.length;el("schedulerTemplateHint").textContent=templates.length?"Somente templates com status aprovado pela Meta são exibidos.":"Nenhum template aprovado está disponível. Cadastre e sincronize um template antes de usar esta opção.";if(!templates.length&&templateRadio.checked){document.querySelector('input[name="schedulerOutsideWindow"][value="nao_enviar"]').checked=true}toggleSchedulerOutsideWindow()}
  function campaignCard(c){var card=document.createElement("article");card.className="scheduler-campaign";var header=document.createElement("header"),title=document.createElement("div"),h4=document.createElement("h4"),date=document.createElement("time"),status=document.createElement("span");h4.textContent=c.nome;date.textContent=new Date(c.agendada_para).toLocaleString("pt-BR");status.className="scheduler-status"+(c.status==="concluida"?" is-complete":c.status==="cancelada"?" is-cancelled":"");status.textContent=schedulerStatusName(c.status);title.append(h4,date);header.append(title,status);var instruction=document.createElement("p");instruction.textContent=c.instrucao_ia;var counts=document.createElement("div");counts.className="scheduler-counts";[["Destinatários",c.total_destinatarios],["Enviadas",c.total_enviados],["Ignoradas",c.total_ignorados],["Falhas",c.total_falhas]].forEach(function(item){var span=document.createElement("span");span.textContent=item[0]+": "+item[1];counts.appendChild(span)});var footer=document.createElement("footer");if(c.status==="agendada"){var edit=document.createElement("button");edit.type="button";edit.className="btn btn-ghost btn-small";edit.textContent="Editar";edit.addEventListener("click",function(){startEditScheduledCampaign(c)});footer.appendChild(edit)}if(c.status==="agendada"||c.status==="processando"){var cancel=document.createElement("button");cancel.type="button";cancel.className="btn btn-ghost btn-small";cancel.textContent="Cancelar";cancel.addEventListener("click",function(){cancelScheduledCampaign(c.id,c.nome).catch(function(error){schedulerFeedback(error.message||String(error),true)})});footer.appendChild(cancel)}card.append(header,instruction,counts,footer);return card}
  function renderSchedulerCampaigns(){var wrap=el("schedulerCampaigns"),campaigns=(state.agendador&&state.agendador.campanhas)||[];wrap.innerHTML="";if(!campaigns.length){var empty=document.createElement("p");empty.textContent="Nenhuma programação criada.";wrap.appendChild(empty);return}campaigns.forEach(function(c){wrap.appendChild(campaignCard(c))})}
  async function loadScheduler(){schedulerFeedback("Carregando programações...");var data=await rpc("adm_atendimento_agendador_contexto_rpc",{});if(!data.ok)throw new Error(data.error);state.agendador=data;renderSchedulerTemplates();renderSchedulerCampaigns();schedulerFeedback("")}
  async function openScheduler(){el("schedulerDate").value=el("schedulerDate").value||schedulerDefaultDate();renderSchedulerContacts();var dialog=el("schedulerDialog");if(!dialog.open)dialog.showModal();try{await loadScheduler()}catch(error){schedulerFeedback(error.message||String(error),true)}}
  function resetSchedulerForm(){state.editCampaign=null;el("schedulerForm").reset();el("schedulerDate").value=schedulerDefaultDate();document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=false});el("schedulerAudienceHint").textContent="";el("schedulerSubmit").textContent="Programar envio";el("schedulerCancel").textContent="Fechar";toggleSchedulerAudience();toggleSchedulerOutsideWindow();renderSchedulerContacts()}
  function closeScheduler(){resetSchedulerForm();if(el("schedulerDialog").open)el("schedulerDialog").close()}
  function cancelSchedulerForm(){if(state.editCampaign){resetSchedulerForm();schedulerFeedback("Edição cancelada.")}else closeScheduler()}
  function startEditScheduledCampaign(c){state.editCampaign=c;el("schedulerName").value=c.nome||"";el("schedulerDate").value=schedulerLocalDate(c.agendada_para);el("schedulerInstruction").value=c.instrucao_ia||"";document.querySelector('input[name="schedulerOutsideWindow"][value="'+c.fora_janela_acao+'"]').checked=true;if(c.template&&c.template.id)el("schedulerTemplate").value=c.template.id;document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.disabled=true});el("schedulerContacts").hidden=true;el("schedulerAudienceHint").textContent="Os "+c.total_destinatarios+" destinatários atuais serão preservados durante a edição.";el("schedulerSubmit").textContent="Salvar alterações";el("schedulerCancel").textContent="Cancelar edição";toggleSchedulerOutsideWindow();schedulerFeedback("Editando: "+c.nome);el("schedulerName").focus()}
  function toggleSchedulerAudience(){var selected=document.querySelector('input[name="schedulerAudience"]:checked');el("schedulerContacts").hidden=!selected||selected.value!=="selecionados"}
  function toggleSchedulerOutsideWindow(){var selected=document.querySelector('input[name="schedulerOutsideWindow"]:checked');el("schedulerTemplateField").hidden=!selected||selected.value!=="template"}
  async function createScheduledCampaign(event){event.preventDefault();schedulerFeedback("");var audience=document.querySelector('input[name="schedulerAudience"]:checked').value,outside=document.querySelector('input[name="schedulerOutsideWindow"]:checked').value,selected=Array.from(el("schedulerContacts").querySelectorAll('input[type="checkbox"]:checked')).map(function(input){return Number(input.value)});if(!state.editCampaign&&audience==="selecionados"&&!selected.length){schedulerFeedback("Selecione pelo menos um contato.",true);return}var localDate=el("schedulerDate").value;if(!localDate){schedulerFeedback("Escolha a data e o horário.",true);return}var submit=el("schedulerSubmit"),editing=state.editCampaign;submit.disabled=true;submit.textContent=editing?"Salvando...":"Programando...";try{var common={p_nome:el("schedulerName").value.trim(),p_instrucao_ia:el("schedulerInstruction").value.trim(),p_agendada_para:new Date(localDate).toISOString(),p_fora_janela_acao:outside,p_template:outside==="template"?Number(el("schedulerTemplate").value):null},data;if(editing){common.p_campanha=editing.id;data=await rpc("adm_atendimento_agendamento_editar_rpc",common)}else{common.p_publico_tipo=audience;common.p_conversas=selected;data=await rpc("adm_atendimento_agendamento_criar_rpc",common)}if(!data.ok)throw new Error(data.error);resetSchedulerForm();await loadScheduler();schedulerFeedback(editing?"Programação atualizada com sucesso.":"Programação criada para "+data.total_destinatarios+" contato(s).") }catch(error){schedulerFeedback(error.message||String(error),true)}finally{submit.disabled=false;submit.textContent=state.editCampaign?"Salvar alterações":"Programar envio"}}
  async function cancelScheduledCampaign(id,name){if(!confirm('Cancelar a programação "'+name+'"? Mensagens já enviadas não serão afetadas.'))return;var data=await rpc("adm_atendimento_agendamento_cancelar_rpc",{p_campanha:id});if(!data.ok)throw new Error(data.error);schedulerFeedback("Programação cancelada.");await loadScheduler()}
  async function init(){try{state.session=readSession();if(!state.session){location.href="../";return}var admin=await rpc("adm_contexto_rpc",{});if(!admin.ok||!Array.isArray(admin.areas)||(admin.areas.indexOf("atendimento")<0&&admin.areas.indexOf("admin")<0))throw new Error("Sem permissão para Atendimento");state.contexto=await rpc("adm_atendimento_contexto_rpc",{});if(!state.contexto.ok)throw new Error(state.contexto.error);el("adminIdentity").textContent=(state.contexto.atendente&&state.contexto.atendente.nome)||(state.session.user&&state.session.user.email)||"Turbo Tiger";setAttendantStatus((state.contexto.atendente&&state.contexto.atendente.status)||"offline");el("agentStatus").disabled=!currentAttendant();el("agentStatus").addEventListener("change",function(){saveAttendantStatus()});state.serverUrl=await rpc("app_config_buscar_rpc",{p_categoria:"turbotiger_urls",p_tipo:"servidor_whatsapp"});if(typeof state.serverUrl!=="string"||!state.serverUrl)throw new Error("Servidor de atendimento não configurado");await initializePulse();await loadConversations();setInterval(syncAutomatically,3000);setInterval(updateSelectedTimeState,1000);document.addEventListener("visibilitychange",function(){if(!document.hidden)syncAutomatically()});window.addEventListener("beforeunload",releaseAllMediaUrls)}catch(error){el("pageStatus").textContent=error.message||String(error);el("pageStatus").classList.add("is-error")}}
  document.querySelectorAll(".queue-button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".queue-button").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.setor=b.dataset.sector;loadConversations().catch(alert)})});document.querySelectorAll(".channel-tab").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll(".channel-tab").forEach(function(x){x.classList.remove("is-active")});b.classList.add("is-active");state.canal=b.dataset.channel;renderList()})});document.querySelectorAll('input[name="schedulerAudience"]').forEach(function(input){input.addEventListener("change",toggleSchedulerAudience)});document.querySelectorAll('input[name="schedulerOutsideWindow"]').forEach(function(input){input.addEventListener("change",toggleSchedulerOutsideWindow)});el("conversationSearch").addEventListener("input",renderList);el("reloadButton").addEventListener("click",function(){loadConversations().catch(alert)});el("takeConversationButton").addEventListener("click",function(){toggleConversationAssignment().catch(alert)});el("messageForm").addEventListener("submit",function(e){sendMessage(e).catch(alert)});el("noteForm").addEventListener("submit",function(e){saveNote(e).catch(alert)});el("schedulerButton").addEventListener("click",function(){openScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerClose").addEventListener("click",closeScheduler);el("schedulerCancel").addEventListener("click",cancelSchedulerForm);el("schedulerReload").addEventListener("click",function(){loadScheduler().catch(function(error){schedulerFeedback(error.message||String(error),true)})});el("schedulerForm").addEventListener("submit",createScheduledCampaign);el("schedulerDialog").addEventListener("click",function(event){if(event.target===el("schedulerDialog"))closeScheduler()});el("logoutButton").addEventListener("click",function(){clearSession();location.href="../"});el("templatesButton").addEventListener("click",function(){alert("Gestão de templates será aberta na próxima etapa de configuração da Meta.")});el("chooseTemplateButton").addEventListener("click",function(){alert("Selecione um template aprovado quando a janela de 24 horas estiver fechada.")});el("settingsButton").addEventListener("click",function(){alert("Configurações de canais, setores e atendentes são restritas à supervisão.")});init();
})();
